### ISSUE TITLE
Automatic type conversion in bs.send

### ISSUE THREAD

**Issue by arnarthor** [cristianoc/genType#101]
Is it possible to have the automatic type conversion happen in `[@bs.send]` externals?

```reason
[@genType]
type config = {
  apiKey: string,
  authDomain: string,
  [@genType.as "databaseURL"]
  databaseUrl: string,
  storageBucket: string,
  projectId: string,
  messagingSenderId: string,
};

[@genType.import "firebase"] [@bs.module "./Firebase.gen.js"]
external initializeApp: config => t = "";
```

This works fine where the config parameter is converted from a Record to a JS object when calling the function initializeApp.

Is it possible to achieve the same with this code? 

```reason
[@genType]
type settings = {timestampInSnapshots: bool};

[@genType] [@bs.send] external settings: (firestore, settings) => unit = "";
```

Adding `[@genType]` to `[@bs.send]` does not do any type conversion for me.

**Comment by cristianoc** [comment]
That’s not supported yet, and I had a question on how to express that kind of object access import.
See also https://github.com/cristianoc/genType/issues/99

**Comment by cristianoc** [comment]
@arnarthor supporting `bs.send` would be possible. Still thinking about a more natural way of expressing the same binding.

Somehow using `bs.send` does not seem clearer than writing the analogue function on the JS side:
```js
var settings = (firestore,s) => firestore.settings(s);
```
and importing it via genType as a function. Not much more to type, and zero magic.

So, I'm unsure at this stage what's best. Ideally, there would be a canonical way to represent classes with methods on the Reason side, at which point both import and export could be implemented and behave as one would expect.

**Comment by arnarthor** [comment]
Yeah absolutely. It's easy to fix on the JS side. Just wondering if I could skip that part for 3rd party packs if I have a full Reason project and only use genType to do automatic conversions in my bindings.

No blocker though, it's a really easy fix.

**Comment by cristianoc** [comment]
Merging into https://github.com/cristianoc/genType/issues/99.
