### ISSUE TITLE
[@bs.module] must be relative to root dir

### ISSUE THREAD

**Issue by ulrikstrid** [cristianoc/genType#106]
Not sure if this is a bug or if it just needs to be documented.

When creating a binding to a react component I had to do this: `[@bs.module "./components/PowerBi.gen"]`, I thought it would be relative to the file.

My structure is something like this:
```
src
- components
  - PowerBi.re
...
App.re
```

**Comment by cristianoc** [comment]
@ulrikstrid that is normally not required, and is pretty much independent from genType itself: that's the way to tell Bucklescript where to find the generated file.

Quick question: are you using `"in-source": true` ? That's a requirement.

**Comment by ulrikstrid** [comment]
@cristianoc It's the same code as in #105 and for more context the code have to look like this: `[@genType.import "./PowerBi"] [@bs.module "./components/PowerBi.gen"]` so I guess genType actually handels this correctly but not bucklescript.

Yes, I'm using `"in-source": true`

**Comment by cristianoc** [comment]
@ulrikstrid presumably there's a `PowerBi.js` file: where is it located?
Also, could you paste the generated `.bs.js` file too?

**Comment by ulrikstrid** [comment]
With the `1.6.1` release I tried to use genType again with my module. This is my working binding:
```ocaml
/* src/components/PowerBi.re */
[@genType.import "./PowerBi"] [@bs.module "../components/PowerBi.gen"]
external make:
  (~accessToken: string, ~reportId: string, ~groupId: string, 'a) =>
  ReasonReact.component(
    ReasonReact.stateless,
    ReasonReact.noRetainedProps,
    ReasonReact.actionless,
  ) =
  "";
```
It seems like this `[@bs.module "../components/PowerBi.gen"]` have to be relative to where it's used as all my `PowerBi` stuff is inside of a "components" folder and it's used from "pages".

PowerBi.gen.js:
```js
/* Untyped file generated by genType. */

import PowerBi from './PowerBi';

import * as React from 'react';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(accessToken, reportId, groupId, children) { return ReasonReact.wrapJsForReason(PowerBi, {accessToken: accessToken, reportId: reportId, groupId: groupId}, children); };
```
The import in my `src/pages/Reports` seems to be a 1-1 to `[@bs.module "../components/PowerBi.gen"]`:
`import * as PowerBiGen from "../components/PowerBi.gen";`
If I change it to what I would expect `[@bs.module "./PowerBi.gen"]` I get this import instead:
`import * as PowerBiGen from "./PowerBi.gen";`

**Comment by cristianoc** [comment]
@ulrikstrid could you also paste `PowerBi.bs.js`?

**Comment by ulrikstrid** [comment]
PowerBi.bs.js:
```js
// Generated by BUCKLESCRIPT VERSION 4.0.9, PLEASE EDIT WITH CARE
/* This output is empty. Its source's type definitions, externals and/or unused code got optimized away. */
```

**Comment by cristianoc** [comment]
@ulrikstrid I think I understand now. You're saying that the argument to bs.module is relative to where `PowerBi.re` is used `from`.
To confirm: is it true that if it's used separately from 2 different directories, then there's no correct annotation that will work? And this issue will show up independently from genType.

My suggestion here is to have `make` be defined locally by adding
```
let make = make;
```
At that point, everything should be local, and `PowerBi.bs.js` won't be empty anymore.

CC @bobzhang

**Comment by cristianoc** [comment]
Can you think of some words to add to the README to help others too?

**Comment by bobzhang** [comment]
or just add a mli file using `val make : ...` should also work

**Comment by cristianoc** [comment]
@bobzhang adding an interface file with identical type declaration changes the semantics? Is this intentional behaviour?

**Comment by bobzhang** [comment]
>adding an interface file with identical type declaration changes the semantics? Is this intentional behaviour?
 
This indeed could cause some suprise, should be improved
