### ISSUE TITLE
DefinitelyTyped/flow-typed integration

### ISSUE THREAD

**Issue by thangngoc89** [cristianoc/genType#111]
I watched your talk at Pusher about genType and its future. There was mentions about integrating with DefinitelyTyped/flow-typed. Do you have any concrete plan about it?

**Comment by cristianoc** [comment]
@thangngoc89 see https://github.com/cristianoc/genType/issues/95 as a more general first step in this direction.
One observation is that quality Reason bindings that people write tend to be different than an automatic translation from the DefinitelyTyped/Flow-typed would look like.
Another question is on the difference between an untyped libraries with some best-effort types retrofitted, and an end-to-end typed library.
So the first step, outlined in https://github.com/cristianoc/genType/issues/95, is to study what a typed library would look like, and how to publish it to npm.

It seems that DefinitelyTyped/flow-typed could be useful to bootstrapping the process, better than starting from scratch in many cases. And that is where they will likely feature.

Likely it will take a little time to get there.

**Comment by cristianoc** [comment]
Closing this as a subset of DefinitelyTyped/flow-typed.
