### ISSUE TITLE
Import record types from other files

### ISSUE THREAD

**Issue by OAGr** [cristianoc/genType#116]
I'm not sure if this is similar to https://github.com/cristianoc/genType/issues/43, but it seems to be an issue for me on the most recent release.

I've noticed that when I use [@genType] on a function that uses a record defined in the same file, then the .gen.js file converts the record type. However, if the function imports the record from another file, then the .gen.js file does not convert the record type input/output. 

This is shown in the bottom image. The top row is for ``Test2.re``, which imports ``fact``. It's ``gen.js`` file, on the right, just references the ``bs.js`` functions instead of converting them into js. ``Test1.re`` is otherwise identical but includes the record.

![image](https://user-images.githubusercontent.com/377065/50405369-695cc400-07ab-11e9-8950-ff0c55d3bf0e.png)

Am I doing something wrong here?

Some info:
I'm using gentype version 1.6.1.
My bsconfig: 
```
{
  "name": "reason",
  "version": "0.1.0",
  "sources": [{
      "dir": "src",
      "subdirs": true
    },
    {
      "dir": "__tests__",
      "type": "dev"
    }
  ],
  "package-specs": {
    "module": "commonjs",
    "in-source": true
  },
  "suffix": ".bs.js",
  "bs-dependencies": [
    "@glennsl/bs-jest",
    "@glennsl/bs-json",
    "rationale"
  ],
  "warnings": {
    "error": "+101"
  },
  "namespace": true,
  "refmt": 3,
  "gentypeconfig": {
    "language": "untyped",
    "shims": {},
    "debug": {
      "all": true,
      "basic": true
    }
  }
}
```

**Comment by cristianoc** [comment]
@OAGr I can't repro. Can you confirm that type `fact` in `Test1.re` is annotated with `[@genType]`?
Or, would you do a PR adding those files to `examples/untyped-react-example/` to check that it repros in CI?

**Comment by OAGr** [comment]
Thanks for responding so quickly!

I made the change, but couldn't get the example to generate the new gen files. I ran ``npm run webpack`` in one terminal, and ``npm start`` in another, but the .gen files didn't generate. 

Code in this branch:
https://github.com/OAGr/genType/tree/issue-116-test

**Comment by cristianoc** [comment]
@OAGr I've created a pull request here: https://github.com/cristianoc/genType/pull/120.
Looks like the conversion gets generated.

**Comment by OAGr** [comment]
Yep, you're right. I'm not sure what the difference is, may try to debug later.

**Comment by cristianoc** [comment]
@OAGr  This should work from a fresh checkout.
```sh
cd genType
npm install
npm run build
npm run install:examples
npm run build:examples
```

**Comment by cristianoc** [comment]
This might be it:
  https://github.com/cristianoc/genType/commit/29ce1e64a65a8afea2da3899fd177028bfa9e2bb

Closing optimistically, please reopen if it happens again.
