### ISSUE TITLE
gentype 1.6.0+ & create-react-app 1.x breaks b/c of eslint `import/first` rule

### ISSUE THREAD

**Issue by peterpme** [cristianoc/genType#125]
Hey,

I've recently upgraded gentype to 2.2.2 and now all my *.gen.js files are failing to compile b/c of `create-react-apps` `import/first` rule:

```
Line 10:  Import in body of module; reorder to top  import/first
Line 13:  Import in body of module; reorder to top  import/first
Line 16:  Import in body of module; reorder to top  import/first
```

Unfortunately create-react-app 1.x doesn't support `.eslintignore` file so my options are either to upgrade create-react-app or downgrade gentype.

Is there anyway we can auto-add `eslint-ignore` to the top of every `.gen.js` file?

I am using gentype + flow.

Falling back to 1.5.0 works.

Thanks!

**Comment by cristianoc** [comment]
@peterpme would you provide an example that triggers the issue?
There might be tension between this moving the imports up and https://github.com/cristianoc/genType/issues/102 moving the imports down, so I was wondering whether your use case falls in the middle.

**Comment by cristianoc** [comment]
Specifically, there was this required changed:
https://github.com/cristianoc/genType/commit/ddf393944f1d17183d2994b4076dfada9d1151bf

**Comment by cristianoc** [comment]
Incidentally, do you know how to turn on the eslint errors on a sample project, so this can then go in CI?

**Comment by peterpme** [comment]
Hey @cristianoc,

Thank you for the speedy response! 

I've created [this repo](https://github.com/peterpme/gentype-create-react-app-test-demo) that mimics the same setup I have running in my app.

Although I can't recreate the `import/first` issue despite importing a different component into my reason flow:

- Hey.js
- Hey.re wrapper
- Greeting.re reason component importing <Hey />

We can easily ignore eslint errors by adding the pragma:

```/*eslint-disable */```

to the top of every file.

I hope this is helpful. I'll be on all day today. Thank you!

**Comment by cristianoc** [comment]
Looks like `eslint-disable` is quite fiddly, and does not want any characters around it, not even `/** eslint-disable */`.
Np added after the heder, instead of inside the header, in *eslint-disable */.

**Comment by cristianoc** [comment]
@peterpme do you need a new release soon?

**Comment by peterpme** [comment]
@cristianoc 😍 thank you so much!

I would appreciate a release by tomorrow when I'm back at work, but do not expect it. Thank you!!!

**Comment by cristianoc** [comment]
In release 2.3.0, which incidentally was needed for a fix.

**Comment by cristianoc** [comment]
Thanks for spotting the issue!
