### ISSUE TITLE
The system cannot find the path specified.

### ISSUE THREAD

**Issue by IvanRodriCalleja** [cristianoc/genType#134]
I am trying to configure a project with genType and when i execute the project it raise "The system cannot find the path specified." and it no generates anything. I downloaded the genType repo to execute the examples and i get the same message.

The bs-platform is "4.0.18" and the genType is "2.6.0"

My genTypeConfig in bsconfig.js is:

```
"gentypeconfig": {
    "language": "typescript",
    "module": "es6",
    "importPath": "relative",
    "shims": {
      "ReasonPervasives": "ReasonPervasives",
      "ReactEvent": "ReactEvent"
    },
    "debug": {
      "all": false
    },
    "exportInterfaces": false
  },
```

What am i doing wrong to get this message?

**Comment by cristianoc** [comment]
The example projects in the genType repo are set up to use the current version not in npm yet, to run tests in CI.
So one needs to build genType in the root of the project with `npm install` and `npm run build`.

Alternatively, set up the example projects using the npm version of genType as described in the README.
