### ISSUE TITLE
Property 'opaque' is missing in type 'Element' but required in type 'reactElement'

### ISSUE THREAD

**Issue by nhducit** [cristianoc/genType#140]
@loganfromlogan @cristianoc regarding this issue https://github.com/cristianoc/genType/issues/135 after add new shim and update bsconfig.json file. the original error gone but I get this error when consume Core.gen.tsx file in another tsx file.

```
TS2741: Property 'opaque' is missing in type 'Element' but required in type 'reactElement'.
```

reproduce PR
https://github.com/cristianoc/genType/pull/139/files#diff-f988f214e8cf5169dfa6d9b20198380eR74

**Comment by cristianoc** [comment]
@nhducit  @loganfromlogan I lost track a bit of all the closed issues, so I'll comment on this one which is open.

In relation to the example https://github.com/cristianoc/genType/pull/139 I've looked at how one represents the desired type in TS and found this article:
https://medium.com/@martin_hotell/react-children-composition-patterns-with-typescript-56dfc8923c64

Taking a leaf from that book, one can define the shim as:
```
import { ReactNode } from 'react';

export type reactElement = ReactNode;
```

That takes care of the issue in the example mentioned above.
But you might have encountered more than one issue, so just let me know here.

**Comment by nhducit** [comment]
thank you @cristianoc. the issue is fixed now. should I create new PR to typescript example? cc @loganfromlogan

**Comment by cristianoc** [comment]
Great!
Would you add your example too to the PR, so there’s an illustration of the shims in use.

**Comment by nhducit** [comment]
Sure!
