### ISSUE TITLE
Does not generate type for JS.t

### ISSUE THREAD

**Issue by nhducit** [cristianoc/genType#143]
this `re` file generate empty `.bs.js` file and  does not generate `.gen.ts` file. is it an expected result?

Use case: I want to migrate theme configuration from JS to reason and use gentype to generate Typescript type to reuse in other Typescript files

typescript
```
const theme = {
  borderColor: '#BF67AD',
  borderRadius: '50%',
  text: {
    black: '#333333',
  },
  headerHeight: 65,
  footerHeight: 25,
  color: {
    black: '#333333',
  },
}
```

re
```
[@gentype]
type theme = {
  .
  // https://bucklescript.github.io/docs/en/object-2#actual-solution
  "borderColor": string,
  "borderRadius": string,
  "headerHeight": int,
  "footerHeight": int,
  "text": {. "black": string},
  "color": {
    .
    "black": string,
  },
};
```

**Comment by nhducit** [comment]
oop, I misspelled `gentype` it should be `genType`. thanks @cristianoc

**Comment by cristianoc** [comment]
It's legit enough that I decided to support it, as it's bound to happen.
