### ISSUE TITLE
Cannot find module './Js.gen'

### ISSUE THREAD

**Issue by loganfromlogan** [cristianoc/genType#150]
When assigning a type to use `Js.Dict.t` the generated typescript file includes this import statement `import {Dict_t as Js_Dict_t} from './Js.gen'`, which generates the error `Cannot find module './Js.gen'`

Types being used:
```reason
[@genType]
type connectionTypes = array(connectionType);

[@genType]
type connectionParams = Js.Dict.t(string);

[@genType]
type connection = {
  .
  "name": string,
  "status": connectionStatus,
  "type": connectionType,
  "parameters": connectionParams,
};
```

Full error:
```
/Users/logan/code/scdt-v1/src/utils/Types.gen.tsx
Type error: Cannot find module './Js.gen'.  TS2307

    1 | /* TypeScript file generated by genType. */
    2 | 
  > 3 | import {Dict_t as Js_Dict_t} from './Js.gen';
      |                                   ^
```

**Comment by benadamstyles** [comment]
Have you added a Js shim file?

**Comment by loganfromlogan** [comment]
I have not. In my ignorance I didn't think of that. Thanks @benadamstyles

**Comment by nhducit** [comment]
@loganfromlogan I have the same issue when using genType with bs-json. I'm curious what is the content of `Js.shim` file. I'm using genType with typescript btw

**Comment by benadamstyles** [comment]
@nhducit Personally, I just add types to the shim as and when I need them. For example, one of my projects has this:

```js
// @flow strict

export type Dict_t<T> = {[string]: T}

export type Promise_t<T> = Promise<T>

export type Exn_t = Error
```

At some point, I've received errors about each of these 3 types being missing, so I've added them to this shim file.

**Comment by cristianoc** [comment]
@nhducit here's an example shim file for `Js.Json.t`: https://github.com/cristianoc/genType/commit/fce38849dc9a853a72b6c9b03762293f63768ccf.

Not sure though what's the idea of exposing it to TypeScript, as there's no magic way of typing json startically.

**Comment by nhducit** [comment]
I ran into another issue genType import as Js_null from shim file. Typescript does not allow to use null as type name.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nhducit** [comment]
About the JSON type in typescript. I'm using JSONValue type from ”ky” package 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by cristianoc** [comment]
@nhducit one can use `Js.Null.t`, which is the same as `Js.null`, but does not use the keyword `null`: https://github.com/cristianoc/genType/commit/8ea2acbb41491572dc53a69e462a8ed46fbfae97.

If there's something forcing `Js.null` directly, I can add support at a deeper level.

**Comment by cristianoc** [comment]
@nhducit also wanted to double check that you do want to use `null` and not `nullable`, the former includes only `null` and the latter `null` or `undefined`.

**Comment by nhducit** [comment]
Here is my usecase, name can be a string/null. I'm not sure which type I should use in reason to achieve the requirements

```
[@genType]
type displayItem = {
  displayId: string,
  name: Js.nullToOption(string),
};
module DisplayDecode = {
  [@genType]
  let decode = json =>
    Json.Decode.{
      displayId: json |> field("displayId", string),
      name: json |> field("name", optional(string)),
    };
};
```

**Comment by nhducit** [comment]
What I want to do is using reasonml, bs-json and genType to do type safe JSON parsing which can be used in Typescript.

**Comment by cristianoc** [comment]
Added full support for `Js.null` https://github.com/cristianoc/genType/commit/0eb5366fe98f78e05b7a71f23b371319571167fe.

The shim approach could create issues as it does not perform conversions when the argument type requires it.

**Comment by cristianoc** [comment]
Closing the issue, as the changes from this discussions are in release https://github.com/cristianoc/genType/releases/tag/v2.11.0.
