### ISSUE TITLE
Is it possible to export module types?

### ISSUE THREAD

**Issue by meafmira** [cristianoc/genType#160]
For example:
```
[@genType]
module type MInner = {let sum: (int, int) => int;};
module type Outer = {module MInner: MInner;};
[@genType]
type outer = (module Outer);
```
generates:
```
export type recType = {| +a: string, +b: number |};

export type outer = {| +MInner: mixed |};
```
where MInner type is `mixed`. Could we replace it with real type? I know it is possible if we use first-class module signatures by replacing MInner type to type `type mInner = (module MInner)` and than replace `(module MInner: MInner)` with `let mInner: mInner`. But is it possible to do this without first class modules?

**Comment by cristianoc** [comment]
If this is still an issue, probably best to re-open an check again with the latest version.
