### ISSUE TITLE
genType not using custom shim

### ISSUE THREAD

**Issue by loganfromlogan** [cristianoc/genType#161]
I may be doing this wrong, but can't get genType to use my shim for Dayjs.

In the file that uses Dayjs:
```reason
[@genType]
type dayjs_t;

[@genType.import ("dayjs", "default")] [@bs.module "./StatusMessages.gen"]
external dayjs: string => dayjs_t = "dayjs";

[@genType] [@bs.send] external format: (dayjs_t, string) => string = "format";
```

bsconfig.json
```json
"shims": {
...
      "Dayjs": "Dayjs",
...
    },
```

Dayjs.shim.ts
```typescript
// tslint:disable-next-line:max-classes-per-file
export abstract class Dayjs {
  protected opaque!: any
}
```

Error
```
Type error: Type 'typeof dayjs' is not assignable to type '(_1: string) => dayjs_t'.
  Property 'opaque' is missing in type 'Dayjs' but required in type 'dayjs_t'.  TS2322

    4 |
    5 | // In case of type error, check the type of 'dayjs' in 'StatusMessages.re' and 'dayjs'.
  > 6 | export const dayjsTypeChecked: (_1:string) => dayjs_t = dayjsNotChecked;
      |              ^
    7 |
    8 | // Export 'dayjs' early to allow circular import from the '.bs.js' file.
    9 | export const dayjs: unknown = dayjsTypeChecked as (_1:string) => dayjs_t;
```

**Comment by cristianoc** [comment]
@loganfromlogan shims are used to export types to JS when the Reason source code is not available, so annotations cannot be added. So e.g. for the standard library.

What would you like to do in your example?

**Comment by loganfromlogan** [comment]
Thanks for jumping in here @cristianoc. I'm actually not using this anymore and can't replicate it at this point. I believe the problem I had is that I had a test written in TypeScript for the StatusMessages.re component and it was having that type conflict. I thought it was due to a lack of a Shim, but maybe that wasn't the case...
