### ISSUE TITLE
run_bsb/clean_bsb, can't find gentype.native.exe, gentype.native

### ISSUE THREAD

**Issue by loganfromlogan** [cristianoc/genType#164]
Trying to utilize the run_bsb and clean_bsb scripts in the examples to enable my project to be run cross-platform. I know using those scripts as is doesn't work for my project because paths are different than the examples. So I was looking for the actual files `gentype.native.exe` and `gentype.native` and couldn't find them anywhere within the gentype repo. Are these generated files, and if so where should I be looking for them?

**Comment by cristianoc** [comment]
Normally one would set up a new project as indicated in https://github.com/cristianoc/genType#installation, which looks for the executable in `node_modules`.

The example projects in the repo are set up slightly differently so they can be run in CI after building the latest executable. To try, the latest executable can be built from the root of the repository with `npm install` and `npm run build`, and will be in the path expected by the example projects.

**Comment by loganfromlogan** [comment]
Okay, I think I was just taking those examples too literally. Working with a backend dev to get my app running on their machine and the server (windows, linux) and thought I needed to do the same as those examples. Thanks.
