### ISSUE TITLE
`bs.deriving accessors` functions are not exported in the generated .re.js file

### ISSUE THREAD

**Issue by moroshko** [cristianoc/genType#165]
Minimal repro:

**A.re**
```re
[@genType]
[@bs.deriving accessors]
type person = {
  name: string
};

[@genType]
let misha: person = {
  name: "Misha"
};
```

The generated `A.re.js` should have the `name` accessor function exported.

**Comment by cristianoc** [comment]
The accessor functions are generated separately and genType does not know of their existence.
One can explicitly use e.g.
```
[@genType]
let nameGet = name;
```

However, since the exported type is explicit
```
export type person = {| +name: string |};
```
the accessor function is not so useful on the JS side, as it's easier to just use `x.name`.
