### ISSUE TITLE
Importing module.exports

### ISSUE THREAD

**Issue by rickyvetter** [cristianoc/genType#167]
```
[@genType.import "foo"][@bs.module "./bar.gen"]
external make: unit => int = "";
```

will generate code that looks like:

```
const foo = require('foo');

// In case of type error, check the type of 'make' in 'bar.re' and 'foo'.
const makeTypeChecked: (void) => number = foo.make;;
exports.makeTypeChecked = makeTypeChecked
```

I can't figure out a way to make this just set `makeTypeChecked` to `foo` instead of `foo.make`. Am I missing something?

**Comment by cristianoc** [comment]
How is the function exported in `foo`? If it's a default export, one could use
```reason
[@genType.import ("./foo", "default")]
```

If it is a CommonJS single export, I don't think there's a way to express that at the moment.
One possibility is to add support for this use case as:
```reason
[@genType.import ("./foo", "")]
```
