### ISSUE TITLE
Imports React even when it doesn't need to?

### ISSUE THREAD

**Issue by justgage** [cristianoc/genType#173]
This is a small thing, that I could somehow add a ignore with eslint (once I can figure out the syntax 🙄) but here it is:

I get this error:
```
[start-js-no-clear] ./src/components/Modal/ModalContainer.gen.js
[start-js-no-clear]   Line 5:  'React' is defined but never used  no-unused-vars
```

The `ModalContainer.gen.js` file looks like this:
```js
/* Untyped file generated by genType. */

import ModalContainer from './ModalContainer';

import * as React from 'react';

import * as ReasonReact from 'reason-react/src/ReasonReact.js';

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function(fullHeight, children) {
  return ReasonReact.wrapJsForReason(
    ModalContainer,
    { fullHeight: fullHeight },
    children,
  );
};
```

The orignial that's it's been generated from: 
```reason
/* Module with the JS component to be wrapped. */
[@genType.import "./ModalContainer"]
/* The make function will be automatically generated from the types below. */
external make:
  (~fullHeight: bool, 'a) =>
  ReasonReact.component(
    ReasonReact.stateless,
    ReasonReact.noRetainedProps,
    ReasonReact.actionless,
  ) =
  "";
```

As you can see React isn't being used. I feel that this isn't a big deal, I'm sure Webpack will probably get rid of it, but still a bit annoying.

I'm using Create React App and my es-lint is:

```
  "eslintConfig": {
    "extends": "react-app"
  },
```

**Comment by cristianoc** [comment]
Thanks for the report.
In fact, importing React is only needed when Flow is used, as Flow treats the JSX notation as implicitly referring to React.
The import can be just omitted when the back-end is `untyped`.
