### ISSUE TITLE
Record wrapped in a Promise doesn't get mapped to a Typescript object

### ISSUE THREAD

**Issue by Yakimych** [cristianoc/genType#175]
Perhaps I am misunderstanding something, but the following generates an empty type file (both TS and flow):
```
[@genType]
[@bs.deriving abstract]
type testType = {
  someString: string,
};
```

Without `[@bs.deriving abstract]` everything works as expected.

**Comment by cristianoc** [comment]
@Yakimych, @bs.deriving abstract is used to derive an abstract type, which is instead accessed with functions such as `someString`.
genType translates that same type, which stays abstract, that's why it's empty.
To access the accessors from JS, you can export them explicitly:
```reason
[@genType]
let someString = someString;
```

**Comment by Yakimych** [comment]
You are right, I confused myself when trying to work around a situation with a Promise. Here is the actual scenario where the types lie to me 🙂 
```
[@genType]
type simpleType = {
  someString: string,
};

// This is correctly inferred as unit => Js.Promise.t(simpleType)
[@genType]
let functionReturningPromiseOfSimpleType = () => {
  Js.Promise.({someString: "someValue"} |> resolve);
};
```
I add a shim for Js.Promise as in [this comment](https://github.com/cristianoc/genType/issues/132#issuecomment-467290219).
In my TypeScript file I pull in the function and call it:
```
import { functionReturningPromiseOfSimpleType } from "./Test.gen";

functionReturningPromiseOfSimpleType()
.then((result: simpleType) =>
  console.log(result.someString)
);
```
In this case I get `undefined` logged to the console, since the type of result is not a record, but an array: `["someValue"]`.
That was the reason why I was trying to work around it by using "record mode" with @bs.deriving abstract, as described in the [bucklescript docs](https://bucklescript.github.io/docs/en/object#record-mode).

Is there any way to get the correct type in TS with a promise?

**Comment by cristianoc** [comment]
@Yakimych you're right and this can indeed be surprising.
Basically, any time there is a type constructor `constr('a)`, in order to perform conversions, genType would need to know how to map arguments of that type. So it would need to know how to do a map of this type:

```reason
let map: ('a => 'b, constr('a)) => constr('b);
```

Of course, there's no way to know how to make maps for arbitrary type constructors.
In practice, this means that even if one writes a shim, conversions won't be generated.

The only solution here is to hard-code important type constructors in genType. And I'm leaning towards doing that for `Js.Promise.t`.

As a workaround, something like this can also be used:
```reason
[@genType]
type t = {x: int};

[@genType.opaque]
type a = t;

[@genType]
let fromT: t => a = x => x;

[@genType]
let toT: a => t = x => x;

type promise = Js.Promise.t(a);

[@genType]
let convert = (x: promise) => x;
```

Here the promise is exported with the abstract type `a`. By keeping the type abstract, no conversion is required (or possible). Instead, functions `toT` and `fromT` can be called to construct/desctruct values of type `a`.

**Comment by Yakimych** [comment]
Ok, thanks for the explanation. I am not sure I understand the workaround though.
I assume that `t` corresponds to my `simpleType`, while `a` is its TypeScript counterpart?
Should I call `fromT` manually in this case and at which point? Do I still need the shim?

**Comment by cristianoc** [comment]
Yes `t` coresponds to `simpleTyp`, and the shim is still needed.
Here's one use from JS:

```javascript
const p : promise = Promise.resolve(fromT({x:3}));
```
Then `p` can be passed to an exported function.

**Comment by Yakimych** [comment]
@cristianoc Unfortunately I am not able to use it this way from JS, since I never have the object as `{x:3}` - this is what I am trying to make my Reason function to return to TS (or rather a Promise wrapping around it). Currently it returns an array with one value: `[3]`.
I've created a [minimal repro](https://repl.it/@Yakimych/React-Typescript-with-Reason-and-genType) in repl, where I am logging both the result that comes from Reason and a after I convert it with `fromT`.
I show the values in the component and log to the console:
```
result: [3]
convertedToA: [undefined]
```
<img width="1429" alt="repl_gentype" src="https://user-images.githubusercontent.com/5010901/55441768-4dd43700-55ac-11e9-972c-d1d393e5d035.png">

**Comment by cristianoc** [comment]
@Yakimych the issue in the minimal repro is that the promise here is exported with a concrete, not an abstract, type:
```reason
[@genType]
let functionThatReturnsPromise = () => {
  // Fetch stuff from an API and decode into type t
  {x: 3} |> Js.Promise.resolve
}

```
so it suffers of the same issues as the earlier examples.

**Comment by cristianoc** [comment]
Meanwhile, I've added first-class support for promises:
https://github.com/cristianoc/genType/commit/fd5d54b9d032dc820e612831d2c6bda44f7865b9

No shims or anything is needed, and the conversions are generated automatically when required.

The workaround was indeed pretty confusing, so this should clean things up.

**Comment by cristianoc** [comment]
Now in version 2.19.0 being published. Feel free to reopen if there are any outstanding issues.

**Comment by Yakimych** [comment]
Wow, works like a charm in repl.it - will try it in our production codebase tomorrow. Thanks!
