### ISSUE TITLE
Having trouble with Reason/JS interop of type

### ISSUE THREAD

**Issue by dhruska** [cristianoc/genType#178]
I'm trying to create a theming system in my app. I have a file where the themes are defined, `T.re`:

```reasonml
[@genType]
type theme = [ | `Light | `Dark];

[@genType]
let themeLight = `Light;

[@genType]
let themeDark = `Dark;
```

The generated `T.gen.js` looks like:
```javascript
import * as TBS from './T.bs';

export type theme = "Light" | "Dark";

export const themeLight: "Light" = "Light";

export const themeDark: "Dark" = "Dark";
```

When I use these values in JavaScript, the expected string representations are used.

TextInput.js:
```javascript
import { themeDark } from T.gen

const TextInput = ({ theme = themeDark }) => {
  console.log(theme) // "Dark"
  ...
}
```

However, when I use the types defined in Reason and then pass them into JS, a number value is used (the one I see in T.bs.js):

Component.re:
```reasonml
  ...
  render: _self => {
    ...
    <TextInput theme=T.themeDark />
  }
```

TextInput.re: (this Reason component is a Reason wrapper for a JS text input)
```reasonml
  let make = (~theme, ...) => {
    Js.log(theme); // 758939798
    ReasonReact.wrapJsForReason(
      ...
```

TextInput.js: Was expecting `Dark`, not `758939798`, so my logic to display certain things based on the theme passed in isn't working.
```javascript
import { themeDark } from T.gen

const TextInput = ({ theme }) => {
  console.log(theme, themeDark) // 758939798, "Dark"
  ...
}
```

Does this make sense? If I didn't explain sufficiently, let me know and I can try to provide more detail.

**Comment by cristianoc** [comment]
@dhruska is the wrapper in `TextInput.re`, the one using `wrapJsForReason` written manually, or generated automatically as described in:
https://github.com/cristianoc/genType#export-and-import-react-components

The difference is that one automatically generated will also perform conversion.

**Comment by dhruska** [comment]
It's written manually, along the lines of:

```reasonml
[@bs.module "./AntdInput"] external input: ReasonReact.reactClass = "TextInput";

[@bs.deriving abstract]
type jsProps = {
  [@bs.optional]
  theme: T.theme,
  [@bs.optional]
  id: string,
  [@bs.optional]
  name: string,
  ...
};

let make =
    (
      ~theme: T.theme=T.themeLight,
      ~id=?,
      ~name=?,
      ...,
      _children,
    ) => {
  ReasonReact.wrapJsForReason(
    ~reactClass=input,
    ~props=
      jsProps(
        ~theme,
        ~id?,
        ~name?,
        ...,
        (),
      ),
    _children,
  );
};
```

I'll try using `genType.import` and see what happens!

**Comment by dhruska** [comment]
So, I've rewritten `TextInput.re` using genType.import, and now in other Reason files where I'm using `TextInput`, I'm getting the error `Warning: Unimplemented primitive used`. I rewrote the component from the above comment to look like the following - does anything look incorrect?

```reasonml
[@genType.import ("./AntdInput", "TextInput")]
external make:
  (
    ~theme: option(T.theme)=?,
    ~id: option(string)=?,
    ~name: option(string)=?,
    'a
  ) =>
  ReasonReact.component(
    ReasonReact.stateless,
    ReasonReact.noRetainedProps,
    ReasonReact.actionless,
  ) =
  "";
```

**Comment by dhruska** [comment]
Ok - I was able to adjust a few things with my file structure and now all is well! Moving to genType.import was the key - thanks for the help!
