### ISSUE TITLE
Support default export of a component with hooks

### ISSUE THREAD

**Issue by baremetalfreak** [cristianoc/genType#179]
Now genType exports a component like any other function. It would be useful to make it a "default" export.

**Comment by petegleeson** [comment]
Could we broaden this issue to be about aligning genType with how Bucklescript supports default exports? Given a reason module like:
```ocaml
[@genType]
let default = 1;
```
Bucklescript 5.0.2 generates:
```js
var $$default = 1;

export {
  $$default ,
  $$default as default, 
}
```
Taking `flow` as an example `genType@^2.19.0` creates a file that looks like:
```js
import * as DefaultExportBS from './DefaultExport.bs';
// line below is a syntax error 
export const default: number = DefaultExportBS.default;
```
There would have to be some special behaviour for `bs.js` files with default exports. One suggestion would be to generate a file that looks like:
```js
import * as DefaultExportBS from './DefaultExport.bs';

const $$default: number = DefaultExportBS.default;
export default $$default;
```

Anyhow, I wanted to say thanks to everyone involved in this project and I am super enthusiastic about it's potential 👏

**Comment by cristianoc** [comment]
@petegleeson that sounds great -- no magic, just support the bucklescript convention.
See: https://github.com/cristianoc/genType/commit/166ef6fb3db30224898fa932687a853934da509c with a couple of examples.

**Comment by baremetalfreak** [comment]
Sounds good, just not sure how such a component will be used _both_ from ReasonML JSX and javascript JSX. https://github.com/cristianoc/genType/commit/166ef6fb3db30224898fa932687a853934da509c#r33202551
If I understand it correctly, `<Component/>` in Reason calls _make_. But now it is called _default_ to become the "default" export in javascript.

**Comment by baremetalfreak** [comment]
OK, looks good!  ✅

**Comment by cristianoc** [comment]
In https://github.com/cristianoc/genType/pull/180.
