### ISSUE TITLE
Consuming nested records in TS

### ISSUE THREAD

**Issue by cem2ran** [cristianoc/genType#184]
It appears that the [@genType] annotation on a nested record only converts the first level, i.e.

```reason
[@genType]
type i18n = {
  first_field: string,
  second_field: string,
  nested_field 
} and nested_field = {
  third_field: string,
};
```

On a record instance of type i18n I'm able to do i18n.first_field and .second_field but not .nested_field.third_field as `nested_field` gives me an array.

I've tried also annotating nested_field with [@genType] but end up with the same result.

For context we have translations defined as a record type, where nested fields express seperate domains. We'd like to also consume them from our TypeScript codebase.

**Comment by cristianoc** [comment]
@cem2ran thanks for the report!
This seems to happen when both types are defined in the same file, and used from another file.
Some type inlining does not reach as far as it should.
