### ISSUE TITLE
propType experiment not working for new ReasonReact hooks components. 

### ISSUE THREAD

**Issue by justgage** [cristianoc/genType#185]
I tried to use the proptypes feature and can't seem to get it to do anything, maybe I'm configuring it wrong? Here's an example repo: https://github.com/justgage/gentype-proptypes-example

**Comment by cristianoc** [comment]
@justgage this was added for class components. I guess functional components will be analogous.

**Comment by justgage** [comment]
Ah that makes sense. Dang.
