### ISSUE TITLE
Expand on usage documentation, and include non-React-specific examples

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [cristianoc/genType#188]
Hi! Trying to get started with genType for the first time, and thought I'd give some feedback, as a newcomer, as to how the docs might be improved.

1. All of the examples — and much of the non-example documentation — seems to revolve around React. It seems a little bit of a heavy dependency; am I to go learn React and web-development in general before I can try out genType? :P

2. There's basically no documentation of `"shims"` beyond, again, mentioning that they're somehow useful for ReasonReact. What *is* a `"shims"` entry, from genType's viewpoint? Why would I add an entry to that array?

3. The documentation is very clear about installation, and fairly clear about usage after you've gotten started, but completely bereft in-between. Let's say I have a file `foo.ml`, and I want a file named `foo.d.ts` generated from it for consumption by JavaScript consumers — what *exact steps* do I take to make that happen?

   I've tried adding `[@@genType]` to a simple variant in my code, but I can't tell from the docs what this is supposed to actually *do*. Does this mean `bsb` is supposed to be spitting out a `.d.ts` file for that module? (... it didn't, but maybe I'm doing something wrong.) Does it mean `bsb` is going to produce different output / additional conversion functions in the `.bs.js` file? (… again, it didn't, but I want to focus on the documentation here.)

4. Speaking of `[@@genType]` — the docs silently assume you're using Reason syntax; and a layman user won't know that the syntax for extension-attributes is different for `.ml` files than it is for `.re` files. At the very least a mention *somewhere* in the README that all of the examples are in Reason syntax — or, better yet, an actual mention of `[@genType]`-before-vs-`[@@genType]`-after — would be great!

Hope some of this was helpful! If I can figure out how to actually get this working in my non-React project, I like to think I might be able to PR some of these improvements at some point, but I can't promise that time away; nonetheless, here's looking forward! <3

**Comment by cristianoc** [comment]
New docs are planned, alongside the other doc efforts to give a uniform view of the ecosystem.
