### ISSUE TITLE
Types for nullable fields

### ISSUE THREAD

**Issue by meafmira** [cristianoc/genType#192]
Now Reason code
```reason
[@genType]
type test = {foo: option(string)};
```
generates this type:
```js
export type test = {| +foo?: string |};
```
but sometimes it's hard to use this type, becase I can't use undefined in field values:
```js
const foo: test = { foo: foo ? foo : undefined }
```
and now I do this:
```js
const foo: test = { ...(foo && { foo }) }
```
but it's weird.
So could we generate this type instead:
```js
export type test = {| +foo?: ?string |};
```
?

**Comment by cristianoc** [comment]
@meafmira that choice is made to preserve the fact that option includes undefined and not null, which has a number of consequences (eg. when a conversion is required). `{| +foo?: string |};` is the type that allows to express that undefined but not null.

For a workaround, it's possible to use:
```reason
type optionString = option(string);

[@genType]
type test = {foo: optionString};
```
which gives

```js
export type optionString = (null | undefined | string);

export type test = { readonly foo: optionString };
```

**Comment by meafmira** [comment]
@cristianoc this doesn't work. With this workaround I can't do this:
```js
const m: test = {}; // error because there is no foo field
```

Maybe it's possible to add some annotation for such cases?

**Comment by meafmira** [comment]
@cristianoc Oh. Now I understand that:
`?string = string | null | undefined`
and
`{ foo?: string } = { foo: string | undefined }`

Ok. This is strict flow. So it's not genType problem. I'll close issue. Thanks for your time

**Comment by janicduplessis** [comment]
@cristianoc What do you think about adding an annotation to optional fields that can contain null?

I have a lot of types defined in TS with `{ foo?: string | null }` but then they create a type error when assigned to a reason type generated with genType like `{ foo: option(string) }`. Maybe something like `[@genType.nullable]`.

**Comment by cristianoc** [comment]
@janicduplessis genType is trying to move towards 1-to-1 correspondence with the bucklescript runtime (i.e. zero runtime cost), instead of adding more if its own annotations. So: @bobzhang any thoughts about this use case for records?

**Comment by janicduplessis** [comment]
Makes sense, I think this is actually more complicated as there are a lot of different way to express nullability in JS / TS.

For example all those different fields could be generated from `option(string)`
```
type A = {
  b: string | null;
  c: string | undefined;
  d: string | null | undefined;
  e?: string | null;
  f?: string | undefined;
  g?: string | null | undefined;
}
```

**Comment by bobzhang** [comment]
in this case, maybe we should spend some time making `string Js.null` easy to work? e.g,
```
type t = | Null | Some of string
```
does it make sense?

**Comment by cristianoc** [comment]
Sounds like the conversation can be continued on bs.
