### ISSUE TITLE
Runtime error for aliased array types

### ISSUE THREAD

**Issue by Coobaha** [cristianoc/genType#196]
Hi, @cristianoc  

I have noticed that genType generates wrong signatures when array type (and maybe other types) is aliased.

It skips runtime conversion but uses expected JS types for the interface - which results in runtime error  🤕 

```reason
module Util = {
  [@gentype]
  type ocaml_array('a) = array('a);
};

type someRecord = {id: int};

type data = Util.ocaml_array(someRecord);

let myData: data = [|{id: 1}|];

[@genType]
let getData = () => myData;
```

produces
```typescript
// tslint:disable-next-line:no-var-requires
const TypesBS = require('./Types.bs');

// tslint:disable-next-line:interface-over-type-literal
export type Util_ocaml_array<a> = a[];

// tslint:disable-next-line:interface-over-type-literal
export type data = Util_ocaml_array<someRecord>;

export const getData: (_1:void) => data = TypesBS.getData;
```

If I add data with normal array type
```reason
type someRecord = {id: int};

type data = Util.ocaml_array(someRecord);

let myData: data = [|{id: 1}|];
let myDataNormalArray = [|{id: 1}|];

[@genType]
let getData = () => myData;

[@genType]
let getDataNormal = () => myDataNormalArray;

```
export for aliased array is fixed :D 
```typescript
// tslint:disable-next-line:interface-over-type-literal
export type Util_ocaml_array<a> = a[];

// tslint:disable-next-line:interface-over-type-literal
export type someRecord = { readonly id: number };

// tslint:disable-next-line:interface-over-type-literal
export type data = Util_ocaml_array<someRecord>;

export const getData: (_1:void) => data = function (Arg1: any) {
  const result = TypesBS.getData(Arg1);
  return result.map(function _element(ArrayItem: any) { return {id:ArrayItem[0]}})
};

export const getDataNormal: (_1:void) => someRecord[] = function (Arg1: any) {
  const result = TypesBS.getDataNormal(Arg1);
  return result.map(function _element(ArrayItem: any) { return {id:ArrayItem[0]}})
};

```

**Comment by cristianoc** [comment]
@Coobaha thanks for the report!

Could you try annotating `someRecord`
```reason
[@genType]
type someRecord = {id: int};
```

Normally when a type is annotated, all the types mentioned in it are assuming as implicitly annotated. Though it might not work for type parameters at the moment. I'll look into it.

**Comment by Coobaha** [comment]
Yes, this produces correct code. My example is not very exact (it produces incorrect TS withotu someRecord type as you've noticed).  I've spotted this with atd generated code - all types are generated correctly, but runtime representation is incorrect. Will try to provide reproducible case.

**Comment by Coobaha** [comment]
@cristianoc https://gist.github.com/Coobaha/b32b8b92decd4a46272bbb2a6e0ce22c

**Comment by cristianoc** [comment]
@Coobaha thanks for the more extensive repro. Looks like there are issues with resolving type parameters across modules. I'll look into that.

**Comment by cristianoc** [comment]
I believe the issue is fixed: https://github.com/cristianoc/genType/pull/197.

**Comment by Coobaha** [comment]
Great! Can you please release it to npm? I will test it

**Comment by cristianoc** [comment]
@Coobaha it's version 2.25.0.

**Comment by Coobaha** [comment]
Now it is visible: ) testing

**Comment by Coobaha** [comment]
Looks good! Thank you for a very quick fix! 👍

**Comment by cristianoc** [comment]
Great! Thanks again for the report.
