### ISSUE TITLE
Using gentype with variants results implicit any error

### ISSUE THREAD

**Issue by lalnuo** [cristianoc/genType#198]
When i have binding:

```
module Foo = {
  [@genType.import ("foo/bar", "default")] [@react.component]
  external make:
    (~direction: [@bs.string] [ | `up | `down | `left | `right]) =>
    React.element =
    "";
};
```

It generates file:

```
/* TypeScript file generated by genType. */
/* eslint-disable import/first */


import {default as makeNotChecked} from 'foo/bar';

const $$toJS577428831 = {"26203": "up", "-1032980382": "down", "-944764921": "left", "-379319332": "right"};

// In case of type error, check the type of 'make' in 'Foo.re' and 'foo/bar'.
export const makeTypeChecked: (_1:{ readonly direction: "up" | "down" | "left" | "right" }) => React_element = makeNotChecked;

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make: unknown = function bar(Arg1: any) {
  const result = makeTypeChecked({direction:$$toJS577428831[Arg1.direction]});
  return result
} as (_1:{ readonly direction: "up" | "down" | "left" | "right" }) => React_element;

import {element as React_element} from '../../../../src/shims/ReactShim.shim';
```

which results typescript error:
```
Foo.gen.tsx(14,45):
TS7017: Element implicitly has an 'any' type because type '{ "26203": string; "-1032980382": string; "-944764921": string; "-379319332": string; }' has no index signature.
```

**Comment by cristianoc** [comment]
Can't repro `Element implicitly has an 'any' type `, does it depend on what's in `foo/bar`?
If there's a simper example without import, or a complete repro, I can take a look.

**Comment by lalnuo** [comment]
@cristianoc sorry i forgot to mention that this only happens when tsconfig.json compiler actions has ”strict”: true or ”noImplicitAny”: true.

**Comment by cristianoc** [comment]
@lalnuo the typescript examples in the repo are configured with `”strict”: true` and `”noImplicitAny”: true`, but I have not seen that message pop up. E.g. this is a similar file generated there: https://github.com/cristianoc/genType/blob/master/examples/typescript-react-example/src/Variants.gen.tsx.

**Comment by lalnuo** [comment]
@cristianoc I created a new repository for reproducing this issue: https://github.com/lalnuo/gentype-198

If you clone it you should be able to reproduce it. Thanks you for your patience :)

**Comment by cristianoc** [comment]
@lalnuo thanks for the repro.
Looks like there's another error first:
```
src/Foo.gen.tsx:5:41 - error TS2307: Cannot find module 'foo/bar'.

5 import {default as makeNotChecked} from 'foo/bar';
```

I wonder if this is causing the second error you're observing.

**Comment by lalnuo** [comment]
@cristianoc i did a small adjustment to my repository, now the first error is gone but

```
src/Foo.gen.tsx:14:45 - error TS7017: Element implicitly has an 'any' type because type '{ "26203": string; "-1032980382": string; "-944764921": string; "-379319332": string; }' has no index signature.

14   const result = makeTypeChecked({direction:$$toJS577428831[Argdirection]});
```

is still happening

**Comment by cristianoc** [comment]
@lalnuo thanks! Are the changes pushed to your repository?

**Comment by lalnuo** [comment]
@cristianoc now they are 🤕

**Comment by cristianoc** [comment]
@lalnuo thanks I can now repro on your repository.
For some reason, the same code does not error when used in the example typescript project in the genType repository even though `noImplicitAny` is set to true.

Not sure how best to silence that error. I've tried a few things, and the type annotation `: { [key: string]: any; }`  seems to do:

```ts
const $$toJS577428831 : { [key: string]: any; } = {"26203": "up", "-1032980382": "down", "-944764921": "left", "-379319332": "right"};
```

Would you try and see if it solves your issue. In which case I'll add that to the generator.

**Comment by cristianoc** [comment]
Found the option that was disabling that error in the genType examples.
Here's a PR that addresses this:
https://github.com/cristianoc/genType/pull/203.

**Comment by cristianoc** [comment]
Merged.
