### ISSUE TITLE
Invalid syntax for untyped backend

### ISSUE THREAD

**Issue by tmattio** [cristianoc/genType#204]
Hi!

When generating code for parametrized functions with the untyped backend, the generated syntax contains what seems to be a type annotation that cause a syntax error when bundling the code.

For the given function:
```ocaml
[@genType]
let column = (name: string, render: 'a => React.element): column('a) => {
  name,
  render,
};
```

The generated code is:
```js
export const column = function <a>(Arg1, Arg2) {
  const result = Curry._2(TableBS.column, Arg1, Arg2);
  return {name:result[0], render:result[1]}
};
```

Which yields the following error:
```
    Module parse failed: Unexpected token (9:31)
    You may need an appropriate loader to handle this file type.
    | import * as TableBS from './Table.bs';
    |
    > export const column = function <a>(Arg1, Arg2) {
    |   const result = Curry._2(TableBS.column, Arg1, Arg2);
    |   return {name:result[0], render:result[1]}
```

Do I need a specific configuration to bundle the output of genType in this case? I checked the demos and can't see a difference with my config.

Thanks :)

**Comment by cristianoc** [comment]
@tmattio thanks for the report!
Indeed that should not be generated for the untyped back-end.
Fix coming.

**Comment by tmattio** [comment]
Thanks!
