### ISSUE TITLE
Impossible to create variant value at runtime

### ISSUE THREAD

**Issue by gaku-sei** [cristianoc/genType#206]
faced this issue in a TypeScript project.

When encapsulating some variants like the following:

`myContext.re`

```reasonml
[@bs.deriving jsConverter]
type state = {value: string};

// Not supposed to be used from the outside
let initialState: state = {value: ""};

type action =
  | Set(string)
  | Clear;

// Not supposed to be used from the outside
let reducer = (_: state, action: action) =>
  switch (action) {
  | Set(value) => {value}
  | Clear => {value: ""}
  };

// Not supposed to be used from the outside
let contextValueToJs = Tuple2.mapFirst(~f=stateToJs);

// Used with the useContext hook
[@gentype]
let context = React.createContext(contextValueToJs((initialState, _ => ())));

// Used as a Provider component
[@genType]
[@react.component]
let make = (~children: React.element) =>
  React.createElement(
    React.Context.provider(context),
    {
      "children": children,
      "value": contextValueToJs(React.useReducer(reducer, initialState)),
    },
  );
```

It will be used like this:

`component.tsx`

```ts
const [state, dispatch] = useContext(context);
// after
dispatch("Clear");
// or
dispatch({ tag: "Set", value: "foobar" });
```

Which will compile, since the generated file will looks like this:

`myContext.gen.tsx`

```ts
const myContextBS = require('./myContext.bs');

// This is wrong at runtime!
export type action = 
  | "Clear"
  | { tag: "Set"; value: string };

//...
```

But it will not work at runtime, since the expected values in Bucklescript are `0` or `[1, "foobar"]`, not `"Clear"`  or `{ tag: "Set", value: "foobar" }`.

The examples using variants don't really help, since they all generate types for the functions additionally to the variants, and as said here #165, `[@bs.deriving accessors]` will not do anything, so I'm somewhat stuck...

I was also wondering if there was a way to rename `tag` to `type` in the generated file, and if there was a way to convert a record to a js object using genType?

**Comment by cristianoc** [comment]
@gaku-sei in this case the global nature of context leaks the bucklescript internal representation of variants to the JS user.

Not sure there's a clean way to retain type safety here.
But at least, one can use a little trick to get access to the internal representation:

```reason
type action =
  | Set(string)
  | Clear;

[@genType]
let internalRepresentation = (x: action) : 'a => Obj.magic(x);
```

So it should be possible to do:
```ts
dispatch(internalRepresentation("Clear"));
```

**Comment by gaku-sei** [comment]
Sounds like a reasonable alternative to me for now (even though I try to avoid the `Obj` module as much as possible), the type safety is preserved (just need to be careful to call `internalRepresentation` in the Typescript file), and the overhead is pretty small.

Thank you very much for your answer @cristianoc
