### ISSUE TITLE
ocaml warning 105 (new bs-platform release)

### ISSUE THREAD

**Issue by Coobaha** [cristianoc/genType#215]
Hi @cristianoc,

```
module Text = {
  [@genType.import ("./Text", "Text")] [@react.component]
  external make: unit => React.element = "";
};

```

This component will get new warning 105
> Warning 105: BuckleScript warning: make : the external name is inferred from val name is unsafe from refactoring when changing value name

The only way to fix it & get valid gentype output is to duplicate external name

```
module Text = {
  [@genType.import ("./Text", "Text")] [@react.component]
  external make: unit => React.element = "make";
};
```

which is still unsafe from refactoring :/ Maybe i am missing something but i've tried several combinations which were not outputting correct .gen files.

**Comment by cristianoc** [comment]
@Coobaha this is a new warning introduced in the new bs-platform release.

When the name of the external is e.g. `make`, then `= ""` and `= "make"` generate the same code.
The former gives a warning, which is newly introduced.

If one prefers to use `= ""`, it's possible to disable the warning in the project config.

**Comment by Coobaha** [comment]
I don't want to disable it for whole project, because it is really helpful. I tried to disable it with [@ocaml.warning "-105"] but it never worked, not sure why.

But with genType.import i am not able to use 
```
module Text = {
  [@genType.import "./Text"] [@react.component]
  external make: unit => React.element = "Text";
};
```

It creates incorrect JS+TS output. I will post example soon

**Comment by cristianoc** [comment]
@Coobaha indeed the `"..."` part is not available in genType, which operates after bucklescript's preprocessor is done, and using a different name just creates an inconsistency, as genType will still generate the original name in the `.gen` file, the only name it has access to, but bucklescript will try to access it with the other name.

**Comment by cristianoc** [comment]
For reference, adding this at the top of the file disables the warning:
```
[@ocaml.warning "-105"];
```

Though somehow this turns off the warning only for command-line compilation. The warning still shows up on vscode.

**Comment by Coobaha** [comment]
Not sure what to do with this issue then.. But it feels that using  `external make: "make"` is more unsafe than just `""`.

`[@ocaml.warning "-105"];` never disables warnings from bsb output to me. Could be that it's not yet supported by bs-platform?

**Comment by bobzhang** [comment]
hi @Coobaha indeed, `[@ocaml.warning "-105"]` won't suppress the warning here (triggered in parsing while the attribute is interpreted in typechecking). To suppress the warning:

```json
 "warnings": {
    "number": "-105"
}
```
We will investigate how to make the warning more intuitive for gentype

**Comment by bobzhang** [comment]
we will try to fix `ocaml.warning "-105"` so that you can at least have file based suppression

**Comment by cristianoc** [comment]
@Coobaha turns out there's a way to get access to the `"..."` part. This is done in https://github.com/cristianoc/genType/pull/217.

**Comment by Coobaha** [comment]
@cristianoc Thanks! it works as expected except `default`, it is not escaped and produces invalid code
`export const default = ...`

**Comment by cristianoc** [comment]
@Coobaha can you give an example of default?
Asking as there's more than one place, e.g. instead of `make` or as `"default"`.

**Comment by Coobaha** [comment]
@cristianoc 
```
  [@genType.import "someModule"]
  external make: unit => string = "default";
```
outputs

```
// In case of type error, check the type of 'default' in 'Checkbox.re' and 'someModule'.
export const defaultTypeChecked: (_1:void) => string = defaultNotChecked;

// Export 'default' early to allow circular import from the '.bs.js' file.
export const default: unknown = defaultTypeChecked as (_1:void) => string;
``

https://www.typescriptlang.org/play/#code/PTAEEkDtQYwQwM4FNQHsBmoAuBPADikgE5GpEA0sAFkjANbY3b4oagDkAJkunAK4AbLO1ABLaOwDCNegCNUADwB0RJCLiROHBKgC2SALKpOgtUoBQSBXjJZYqSAjvdegrABUW02nSScAXKAAFAD6AIz+AG6oopwAlKAAvAB8oE5E4gDmSaAu-EIAcqhY3vR+ANzm5iCgAKLWthx5biJIcEQCONiooHACAqgA7rCiRDCC7WK6NkR26KS6jCjsSrIISgBWCCLoogJIFlYzdjAOTrk8+ViBfJB0kEPQiReuQp4Epb5aiMHhUTHxJKpdJZcpAA

**Comment by cristianoc** [comment]
@Coobaha thanks for that.

There's already a mechanism to support importing a default export: https://github.com/cristianoc/genType/blob/master/examples/typescript-react-example/src/ImportHookDefault.re.

However, it might be possible to support `="default"` as well. In fact, also this:
```reason
[@genType.import "someModule"]
  external default: unit => string = "";
```

**Comment by cristianoc** [comment]
@Coobaha I've added support default import when the value is called `default` in this PR https://github.com/cristianoc/genType/pull/220.

**Comment by cristianoc** [comment]
In 2.31.1.
