### ISSUE TITLE
Confused about importing typescript types

### ISSUE THREAD

**Issue by cician** [cristianoc/genType#218]
Please bear with me as I'm a newbie to both ReasonML and genType. I'm confused because it seems to me that the readme implies I should be able to consume typescript types with something like
```Reason
[@genType.import "./MyMath"]
type complexNumber;
```
but either I'm doing something wrong, it doesn't work, or I'm misunderstanding what it should actually do. Should it automatically generate a type definition that I can use in Reason to allocate new objects etc.? The examples all seem to define the types in reason when importing, which works, but I don't understand how is it different to using Bucklescript's interop directly.

Should this work?
``` typescript
//  Bla.ts
export type MyType = {
	readonly n: string;
}
```
```Reason
// Test.re
[@genType.import ("./Bla", "MyType")]
type myType;

let test : myType = {
	n: "test"
};
```
Here I get the error "Unbound record field n".
Or do I need to do this?
```Reason
[@genType.import ("./Bla", "MyType")]
type myType = {
	n: string
};
```

Exporting on the other hand works and is intuitive. Ultimately what I'm most interested in is consuming js/ts libraries with typings in reasonml and maybe my own typescript code. Should I look elsewhere? I know there's ReasonablyTyped, but it doesn't seem to be currently maintained.

Anyway thanks for making this library. Even if it's just for the exporting reason code to typescript, it makes me more confident investing my time in reasonml.

**Comment by cristianoc** [comment]
@cician your understanding seems correct.
As far as types are concerned, Reason is always the source of truth, and there's no automatic conversion from e.g. TypeScript. A type defined on the TypeScript side is only imported as abstract, meaning on the Reason side you don't know how it's defined.

Instead, if the type is defined on the Reason side, its corresponding type can be used also when importing a TypeScript value. The difference w.r.t. using bucklescript's interop directly is that your types get checked (specifically, in case of inconsistency, a type error should be caught by TypeScript).

As far as the other direction, converting types automatically from TypeScript, there have been a number of lines of work, one of which is ReasonablyTyped. The observation seems to be that this works on simple cases, but it's not so clear how the conversion should work on arbitrary TS types.

**Comment by Coobaha** [comment]
Cristiano was faster, but i decided to post my comment too :D 

Hi @cician 
I am just a genType user - so some things in my answer may not be 100% correct.

genType generates types from Reasonml code to use and typecheck on the other side (JS/Flow/TS). It will never understand external types in Reasonml world (at least now, no idea about future plans), but offers possibility for TypeScript to check genType output.

In your code
```
[@genType.import ("./Bla", "MyType")]
type myType;
```
Creates abstract type, which genType will "link" in generated files to real Bla.MyType.

To use it in Reasonml code you have two options:
1) also use some external function that will return myType (probably some TS function)
2) type it in Reasonml again, but let TS to verify genType output based on usage/bindings
```
[@gentype]
type myType = {
 .
 "n": string
};
```

You can read [here](https://bucklescript.github.io/docs/en/bind-to-global-values#abstract-type) about abstract type

**Comment by cician** [comment]
Thank you for a prompt responses.

I'm more talking to myself here as I'm facing a technology choice for my project. So reassuming:
GenType as it stands does not provide a fuctionality like ReasonablyTyped or ts2fable to automatically generate ReasonML types from TypeScript definitions. No one so far managed to automagically and consistently convert lousier TypeScript type system to the strictier OCaml, so creating and maintaining bindings to js libs is mostly manual labor. Compared to plain BuckleScript interop, there are ways to take advantage of reason-to-typescript export in order to at least enforce some consistency when consuming typescript types and functions with redefined types.

Based on this, it seems relatively easy to write a part of my app in reasonml and consume it from typescript thanks to genType, as long as it's something relatively dependency free, but it could be quite difficult to go 100% reasonml if I'm reliant on a ton of js/ts libs with no bs-* bindings available and cannot afford to write them myself.

**Comment by cristianoc** [comment]
Closing for now. Feel free to re-open for more discussion.
