### ISSUE TITLE
Flow complains about nonstrict-import annotation

### ISSUE THREAD

**Issue by adnelson** [cristianoc/genType#219]
Attempting to get flow to type my codebase, I get:

```
Error: src/reasonml/data/Chart.gen.js:18
 18: // flowlint-next-line nonstrict-import:off
                           ^^^^^^^^^^^^^^^^ Nonexistent/misspelled lint rule. Perhaps you have a missing/extra ','?

Error: src/reasonml/data/Chart.gen.js:21
 21: // flowlint-next-line nonstrict-import:off
                           ^^^^^^^^^^^^^^^^ Nonexistent/misspelled lint rule. Perhaps you have a missing/extra ','?

Error: src/reasonml/data/Chart.gen.js:24
 24: // flowlint-next-line nonstrict-import:off
                           ^^^^^^^^^^^^^^^^ Nonexistent/misspelled lint rule. Perhaps you have a missing/extra ','?
```

I'm using flow version 0.54.1. I attempted to upgrade my version of flow, unfortunately that brought with it a litany of other errors, so I don't know if I can realistically pursue that course at this point. Is there any workaround for this particular error? Failing that, what's the minimum version of flow known to work?

**Comment by cristianoc** [comment]
@adnelson do you also get a config error adding this to `.flowconfig`?
```
[strict]
nonstrict-import
```

I suspect that removing those comments also leads to errors. Not sure when `nonstrict-import` was introduced.

**Comment by adnelson** [comment]
@cristianoc I tried that and got an error `Unsupported config section: "strict"` :( I suspect this comes from the same problem...

**Comment by cristianoc** [comment]
@adnelson yes I think that too.
I think updating Flow would be the only way here. In fact, it could give more safety straight away even before introducing genType.
Unless there's no plan to update the codebase, in which case you could also use straight bucklescript bindings.

**Comment by adnelson** [comment]
I found the minimum version of flow that supports `nonstrict-import`, which is `0.72.0`. Unfortunately, using this breaks type checking on existing code. I'm looking into how easy it would be to fix these errors (they may well be legitimate anyway). I suppose in the worst case I can just use `untyped` and duplicate the types by hand...

**Comment by cristianoc** [comment]
Feel free to re-open for more discussion.
