### ISSUE TITLE
Bucklescript 6 (OCaml 4.06.x) compatibility

### ISSUE THREAD

**Issue by wokalski** [cristianoc/genType#221]
Is `genType` compatible with OCaml 4.06? The current release is compiled against 4.02 which doesn't work with bucklescript beta. I am wondering if it can be compiled against 4.06 at all and if there's a workflow for doing that (I tried with esy but then I noticed that the opam file is empty)

**Comment by cristianoc** [comment]
@wokalski there's this version that compiles with dune on 4.06: https://github.com/cristianoc/genType/pull/100.

The dependencies are tiny:
```
(libraries unix str compiler-libs.common)
```

The only thing, I'm not sure how to set up CI with it, to create releases.

**Comment by wokalski** [comment]
If we use cppo in the source the only concern would be what versioning scheme should be used for 4.06 compatible releases. Alternatively, if we assume that it’s only for people living on the bleeding edge, a complete opam file/esy.json would be sufficient (so that we could use it with opam/esy)

**Comment by cristianoc** [comment]
It would be great to have at least a bleeding edge going, to start with.

**Comment by wokalski** [comment]
Sounds good. Is it okay if I use `ppx_optcomp` (cppo is not supported in `re` files)

**Comment by cristianoc** [comment]
Sounds great.

**Comment by wokalski** [comment]
Until the `4_06_1` branch is merged, using this ppx with Bucklescript 6 involves a few additional steps. 

**For esy users:**

1. Add gentype to your dependencies:

```
{
  "dependencies": { "ocaml": "4.6.x" },
  "devDependencies": {
    "@opam/genType": "cristianoc/genType:genType.opam#4_06_1"
  }
}
```
2. Run `esy` (installs and builds `gentype`)
3. Create a script (I called it `gentype.ppx`) with `esy x gentype.exe "$@"` as contents.
4. Make it executable (with `chmod +x gentype.ppx`)
5. Add the path of the script to your gentype config (inside `bsconfig.json`):
```
  "gentypeconfig": {
    "path": "./gentype.ppx",
```

PS: gentype has been autocorrected to genotype too many times while I was writing this comment!

**Comment by cristianoc** [comment]
Luckily, 4.06 support is a thing now.
