### ISSUE TITLE
react.component externals for non-function components

### ISSUE THREAD

**Issue by rickyvetter** [cristianoc/genType#225]
Currently if you write an external for a React component that requires prop conversions, the output will only work if the component is a function component:

```reason
[@genType]
type buttonType = | Disabled | Active | Primary;

[@react.component]
[@genType.import "./MyComponent"]
external make = (~type_: buttonType) => React.element = "";
```

In this case the generated output will call `MyComponent.make` as a function instead of with React.createElement. I think this inconsistency can cause issues if people aren't looking out for it.

**Comment by cristianoc** [comment]
Explored here: https://github.com/cristianoc/genType/issues/210.

**Comment by cristianoc** [comment]
Explored here: https://github.com/cristianoc/genType/pull/226.

**Comment by cristianoc** [comment]
In https://github.com/cristianoc/genType/pull/226.
