### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by Coobaha** [cristianoc/genType#231]
Hi @cristianoc, i've enabled namespace for reason module
with this module
```reason
[@genType.import "common/components/Spinner"] [@react.component]
external make: (~size: string) => TsReact.element = "default";
```

gentype output is

```js
/* TypeScript file generated by genType. */
/* eslint-disable import/first */


import {default as defaultNotChecked} from 'common/components/Spinner';

// In case of type error, check the type of 'default' in 'Spinner.re' and 'common/components/Spinner'.
export const defaultTypeChecked: (_1:{ readonly size: string }) => MyNamespace_TsReact_element = defaultNotChecked;

// Export '$$default' early to allow circular import from the '.bs.js' file.
export const $$default: unknown = defaultTypeChecked as (_1:{ readonly size: string }) => MyNamespace_TsReact_element;

import {TsReact_element as MyNamespace_TsReact_element} from './MyNamespace.gen';

export default $$default;
```

Please notice that it uses MyNamespace instead of TsReact.

TsReact is a simple module to make ts happy with our bindings
```reason
[@genType]
type element = React.element;

[@genType]
type elementType = React.element;
```

**Comment by Coobaha** [comment]
I was able to workaround this by creating MyNamespace.re that duplicates TsReact code

```
module TsReact = {
  [@genType]
  type element = React.element;

  [@genType]
  type elementType = React.element;
};

```

**Comment by Coobaha** [comment]
I think custom namespace (as string) is causing this issue.

```
Note on custom namespacing: if for some reason, you need a namespace that is different from what your name will produce, you can directly send a string to the namespace option. For example, if your package is a binding named bs-some-thing, you can use "namespace": "some-thing" to get SomeThing namespace instead of BsSomeThing.
```

**Comment by Coobaha** [comment]
Another observation, I have lerna monorepo setup with multiple reason modules, and there is one app that uses them all.
If i compile each package individually it works correctly,
but if i compile top root project, that has reason modules as deps - `genType` outputs incorrect relative paths for shims, which makes ts mad

**Comment by cristianoc** [comment]
@Coobaha after these investigations, do you think that the generation does not behave as expected? Or it behaves as expected and there's some feature/customization missing?

**Comment by Coobaha** [comment]
@cristianoc 
Yes, it doesn’t behave as expected with custom namespace. Output uses invalid imports.

I will setup minimal repo with the issues above tomorrow

**Comment by Coobaha** [comment]
@cristianoc 
https://github.com/Coobaha/gentype-monorepo-issue

Issues are collected in README.md

**Comment by cristianoc** [comment]
@Coobaha just mentioning that his issue was not forgotten. Just, it's non-trivial, and will take a while to unpack.

**Comment by Coobaha** [comment]
@cristianoc  Also noticed that with `namespace: true` 

output is not a valid typescript
```

import {StringId_t as Opaque-BsGentypeIssue_StringId_t} from './Opaque-BsGentypeIssue.gen';
```

```
		"bs-platform": "^5.2.0",
		"gentype": "^2.40.0"
```

**Comment by cristianoc** [comment]
@Coobaha I could not repro on one of the existing projects.
Is the repro the same one pasted above?
https://github.com/Coobaha/gentype-monorepo-issue

I've tried to follow the instructions, but failed with:
```
$ npx lerna exec build

lerna notice cli v3.16.4
lerna info Executing command in 3 packages: "build"
/bin/sh: build: command not found
```

Is there a standalone repro? Not sure what lerna does under the hood.

**Comment by Coobaha** [comment]
@cristianoc `npx lerna exec yarn build`

**Comment by cristianoc** [comment]
Happy to revisit. Feel free to reopen if still a wish.

**Comment by Coobaha** [comment]
Yes this is still an issue in our monorepo codebase @cristianoc, I have found couple of workarounds: creating module with same name as custom namespace and also keeping shim files in root sources folder though.

**Comment by cristianoc** [comment]
@Coobaha I've started do look into this.
First, there was a comment above about import with namespace:true.
Here's an example of importing a type in a prpoject with namespace:true. https://github.com/cristianoc/genType/pull/307.
 So far it looks OK.

Would you suggest what's the next small step to repro an issue?

**Comment by cristianoc** [comment]
(This is based on master, in case recent changes are relevant -- let's discuss about the latest version).

**Comment by Coobaha** [comment]
Have you tried ‘namespace: “custom”’? I will check/update my repo tonight

**Comment by cristianoc** [comment]
@Coobaha just tried `namespace: “custom”` and indeed it creates issues.
Haven't tried that before: so by definition it's currently unsupported.

**Comment by cristianoc** [comment]
For what is worth, I've updated the README to mention this limitation so at least the current state is documented.

**Comment by Coobaha** [comment]
@cristianoc checking my reported issues with recent gentype now

**Comment by Coobaha** [comment]
@cristianoc yeah, it seems to be resolved! i am closing this :) will report new issues here if will find some

**Comment by cristianoc** [comment]
Ooh that was much smoother than I was expecting. Thanks!

**Comment by Coobaha** [comment]
@cristianoc hey, sorry but one issue still there :/ I've pushed deps update to https://github.com/Coobaha/gentype-monorepo-issue

Steps to reproduce:
```
git clone git@github.com:Coobaha/gentype-monorepo-issue.git
cd gentype-monorepo-issue
yarn lerna bootstrap
yarn buld
```

yarn build will build `packages/app` that has other packages as deps, please check `packages/app/src/App.gen.tsx` (it will have wrong imports)

```
/* TypeScript file generated by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const AppBS = require('./App.bs');

import {Demo_t as DemoShimDemo_Demo_t} from './DemoShimDemo.gen';

import {Types_demo as DemoSomePackage_Types_demo} from './DemoSomePackage.gen';

// tslint:disable-next-line:interface-over-type-literal
export type wrongShimImportPath = DemoShimDemo_Demo_t;

export const wrongTsImportsWithCustomNameSpace: (_1:{ readonly size: string }) => DemoSomePackage_Types_demo = function (Arg1: any) {
  const result = AppBS.wrongTsImportsWithCustomNameSpace(Arg1.size);
  return result
};

```

**Comment by cristianoc** [comment]
@Coobaha I had a look at how the project is set up. Looks lerna has some pretty unusual setup -- not even sure why it builds.
Looks like there's nothing in node_modules.

For now, the plan is only to support a straighforward flow for now, as in https://github.com/cristianoc/genType/pull/301.
That's in master but not in a release yet. I'll cut a release.

(Already checked it does not support lerna, as it expects things to be in node_modules).

**Comment by Coobaha** [comment]
lerna+yarn hoists all modules to root node_modules. local packages can be symlinked with `lerna link` command. 
![image](https://user-images.githubusercontent.com/2446638/68732803-250a2a80-05ee-11ea-8d6e-3dc52582109d.png)

**Comment by Coobaha** [comment]
@cristianoc I've tried `3.4.0`

Output is almost there 😅 
```typescript
const AppBS = require('./App.bs');

import {Demo_t as DemoShimDemo_Demo_t} from '@demo/shim-demo/DemoShimDemo.gen';

import {Types_demo as DemoSomePackage_Types_demo} from '@demo/some-package/DemoSomePackage.gen';

```

It misses `src` in path, and uses package namespace for file prefixes.

Correct path will be `@demo/shim-demo/src/Demo.gen` for 
```reason
[@genType]
type wrongShimImportPath = DemoShimDemo.Demo.t;
```

**Comment by Coobaha** [comment]
@cristianoc following your comment https://github.com/cristianoc/genType/issues/308#issuecomment-554380007

It works now 🎉, we are almost there :D shims are still not resolved correctly. 

When compiled from main `package.json` `packages/shim-demo/src/Demo.gen.tsx` gets incorrect shim path:
      `import {t as ToShim_t} from './Shimmed.shim';`

When compiled from module itself path is correct:
      `import {t as ToShim_t} from '../src/shims/Shimmed.shim';`


Path is resolved correctly if shim is located in top folder though (`src` in this case):
```
// Main package.json compilation
import {t as ToShim_t} from './Shimmed.shim';
// Package as root compilation
import {t as ToShim_t} from '../src/Shimmed.shim';
```

P.S. This is reproducible in the same repo, I've updated `genType` version there

**Comment by cristianoc** [comment]
@Coobaha nothing special is done about shims and sub-projects.
In fact, I did not think one should do anything special. So any sub-project is a project which could define its own shims.
Can you explain at a high level what you would expect to happen and the rational about it?
We can also move it to a new issue.
