### ISSUE TITLE
Flatten type "unions" to allow both JSX.Element and string as React component's children

### ISSUE THREAD

**Issue by gaku-sei** [cristianoc/genType#234]
When genType generates the TypeScript type of React component's children, it will always conform to one type only (which is both logic and perfectly fine). For instance:

```reason
[@genType]
[@react.component]
let make = (~children) => <div> children->React.string </div>;
```

will generate something like this:

```tsx
export const X: React.ComponentType<{
  readonly children?: string; 
}>
// ...
```

and

```reason
[@genType]
[@react.component]
let make = (~children) => <div> children </div>;
```

will generate that:

```tsx
export const X: React.ComponentType<{
  readonly children?: JSX.Element;
}>
// ...
```

Again, it's perfectly valid, and there is nothing to complain about here.

But, with the above types, it becomes tedious to use the "generated" Components, since passing string, number, null, or React Element(s) as children to a React Component is very common.

It's actually so very common, that in practice (in TypeScript), most of Components will accept `ReactChild`(ren) as children, where `ReactChild` is defined as follow: `type ReactChild = ReactElement<any> | ReactText;`, that is an union of `JSX.Element`, `string`, and `number`.

I perfectly understand that ReasonML is not that flexible, and that types can't be mixed this way, but I was wondering if there was a way to generate "flat" unions in TypeScript using genType (or BuckleScript??), so that the following:

```reason
// Not actual code
[@genType.flatten]
type children = [  | `string(string) | `element(React.element) ];

[@genType]
[@react.component]
let make (~children: children) => ...
```

would generate the following code in TypeScript (and something similar in Flow):

```ts
export type Children = string | JSX.Element;

export const X: React.ComponentType<{
  readonly children?: Children;
}>

// Some converters would be required to map the children to the actual ReasonML type
```

It would be extremely useful in TypeScript and would keep the type safety in both ReasonML and TypeScript (and Flow), in this case (`[@bs.unwrap]` could work, but we are outside an `external` declaration here).

So, is there a way to achieve this kind of things?

**Comment by cristianoc** [comment]
Merge into https://github.com/cristianoc/genType/issues/239.
