### ISSUE TITLE
What is the proper way to deal with children and typescript ?

### ISSUE THREAD

**Issue by sync** [cristianoc/genType#239]
Wasn't sure what to do when using gentype with a simple reason react component taking children(s).

```
[@react.component]
let make = (~style=?, ~children) => {
  <div ?style className> children </div>;
};

[@gentype]
let default = make;
```

When using from typescript:

```
const { getByTestId, getByText } = render(
  <H1 testID={TestID.fake}>{title}</H1>
);
```

I get the following error: `the type string is not assignable to type element`

I understand why i get the following error, because a children in ReasonReact has to be a React element. 

It can work if doing the following (which seem more like a work around and now I can only provide a string as a children):

```
[@react.component]
let make = (~style=?, ~children) => {
  <div ?style className> children->React.string </div>;
};
```

Then facing issues if for example i want to provide an array of string etc....

Is there something we could do to convert automatically those children to react element... etc... ?

**Comment by gaku-sei** [comment]
Second this. I also opened an issue some days ago: https://github.com/cristianoc/genType/issues/234

**Comment by cristianoc** [comment]
One could try to special-case children, so that when the type on the Reason side is `React.element` then the generated TypeScript will use `React.ReactChild`.
Typing-wise, this seems doable.
One question is whether it's possible to construct a Reason component with child of type `React.element` that goes wrong when one passes a string directly.

**Comment by cristianoc** [comment]
I guess it's OK as `React.string` is the identity and returns `React.element`.

**Comment by cristianoc** [comment]
@sync @gaku-sei take a look here: https://github.com/cristianoc/genType/commit/2168d4d77c4446be2869b85c81b1e60397a50a8a.

Let me know if it covers your needs.

**Comment by sync** [comment]
amazing, testing this now 👍
