### ISSUE TITLE
Question: Why not box all members of a variant in .import ?

### ISSUE THREAD

**Issue by elnygren** [cristianoc/genType#246]
### Background
Status quo from docs: 

>  ```| A | B(int) | C(string)``` has values such as ```"A"``` and 
	```{tag: "B", value: 42}``` and ```{tag: "C", value: "hello"}```.

### Question:
Why not make `| A | B(int) | C(string)` into:

```
{tag: "A", value: undefined}
{tag: "B", value: 42}
{tag: "C", value: "hello"}
```

so we can use switch in TS side:

```
switch (foo.tag) {
  case 'A':
    // TS will now foo.value is undefined here
  case 'B':
    // TS will know value is a number here
  case 'C':
    // TS will know value is a string here
}
```
?

Now the issue is that the boxed and unboxed alternatives need to be processed separately.

**Comment by cristianoc** [comment]
@elnygren it's to keep it consistent with
```reason
| A | B | C
```
as
```reason
"A", "B", "C"
```

Somehow one needs to choose between making `switch` happy and have uniform representation + keeping a compact runtime representation.

**Comment by cristianoc** [comment]
If one really wants to box everything, it's possible to use e.g.
```reason
| A(unit)
```

**Comment by elnygren** [comment]
@cristianoc thanks for the quick reply, and I think the `unit` trick is 👍 👍 here.
