### ISSUE TITLE
Consider emitting `.d.ts` files as output for TypeScript

### ISSUE THREAD

**Issue by kutyel** [cristianoc/genType#25]
Hi! @ryyppy showcased this in [ReactAlicante](http://reactalicante.es/) last weekend, and it was very cool! 😎 

After the talk, we had a very interesting conversation with @ForbesLindesay where he mentioned that it will increase performance if the TypeScript output were only declaration files and not actual source code (like the case with flow).

Maybe we can consider that? This issue is just to keep track of that conversation 😉

**Comment by cristianoc** [comment]
Some code is required to wrap components for ReasonReact, and to perform some type conversions at runtime.

One could in principle generate pairs of files, but perhaps the granularity of .d.ts files can be different.

**Comment by ForbesLindesay** [comment]
Yes, the proposal was to generate a pair of files:

- foo.d.ts - type definitions. Since these don't contain any implementation, they don't get full type checking by typescript
- foo.js - the actual implementation, completely ignored by typescript
- foo.js.flow - optionally also generate flow type definitions

In addition to being faster, typescript and flow are much less likely to break code written to type definitions when they add stricter type checking rules/change their inference engines.

**Comment by cristianoc** [comment]
@kutyel @ForbesLindesay 
What are a couple of idiomatic projects with TypeScript and React? I'd like to look at them and see what the ideal conversion process would look like.

Ideally, we want to support the following conversion process:
1) There is a Parent reactjs component and a Child reactjs component.
2) Delete the Child component and re-write in Reason, with `@genType` annotations. The Parent component does not need to be changed at all.
3) Delete the Parent component and re-write in Reason. Delete the `@genType` annotations from the Reason Child component, as it's not used from JS anymore, so the wrapper artifacts generated become redundant and are now deleted.

The crucial step is 2, where the assumption is that what `@genType` generates is immediately consumable by Parent, i.e. is idiomatic.

**Comment by kutyel** [comment]
I think @jaredpalmer can help with that 😉

**Comment by cristianoc** [comment]
Moving this to the more general issue https://github.com/cristianoc/genType/issues/95.

**Comment by gustavopch** [comment]
@cristianoc Issue #95 was closed without addressing how to emit `.d.ts` AFAICT so this issue should be reopened.
