### ISSUE TITLE
Refactor CI processes to allow 4.02 & 4.06 releases

### ISSUE THREAD

**Issue by ryyppy** [cristianoc/genType#250]
This is how our release process looks like right now:
- Commit latest changes on master
- Use npm to raise the version number, it will add a git version tag and run the `scripts/bump_version_module.js` script to change the `src/Version.re` file
- CIs pick up version tags and do a release build if all tests passed
- CI also checks the `gentype --version` output to make sure we don't release binaries without proper version number.
- If all tests are successful, they push on the Github releases tab with the right package.json version

The npm package release happens manually by running the `scripts/prepare_dist.js` script, which downloads the build artifacts from the github releases section and puts the content into the `dist/vendor-*` directories. It also updates the dist/package.json if necessary.

After that, we do a typical `npm publish dist/`. For 4.06 builds, we have a separate `scripts/prepare_406_dist.js` script, which will add a `-4.06` suffix to the release version number.

I'd like to change the CI system in a way that we have following process:
- Use `esy` to build for 4.02.3 and 4.06.1 with two different esy config files 
- src/Version.re should also contain the ocaml version (e.g. `gentype --version` should yield `2.31.1-4.6` ... we should probably pull this information from an environment variable configured in the `esy.json` files
- Configure Azure Pipelines to run the 4.02 build + tests first, and if this is successful, run the 4.06 build and release to github with following structure: `gentype-[4.02|4.06]-[linux|darwin|win].tar.gz` released to the package.json version number

After that is done, we can use our current npm release processes. As a bonus, it would be great if we could use the `esy npm-release` feature somehow to achieve the same release process as of right now.

Also it would be great if we could run 4.06 builds with our current test infrastructure (not sure how to do that since I have never used a 4.06 based bucklescript release).

\cc @wokalski

**Comment by wokalski** [comment]
>I'd like to change the CI system in a way that we have following process:
>
> - Use esy to build for 4.02.3 and 4.06.1 with two different esy config files

One thing here is that genType doesn't use OMP. In order to use CPPO we'd need to use .ml instead of .re. ppx_optcomp doesn't support 4.02.

I wanted to upstream 4.06.1 support but it was a little bit cumbersome because of that.
