### ISSUE TITLE
Export inner modules as objects

### ISSUE THREAD

**Issue by cristianoc** [cristianoc/genType#253]
This implements a feature request from @sync, to give more idiomatic access to inner modules from JS.

When an inner module (i.e. a module declared within a file) contains values exported to JS, also generate an object with the name of the module and the exported values.

So for example:
```reason
module Inner = {
  [@genType]
  let x = 34;
}
```
should generate some additional code:
```js
export const Inner : { x : number } = { x : Inner_x };
```

If the new representation of inner modules is available, this is optimized to:
```js
export const Inner : { x : number } = ThisFileBS.Inner;
```

**Comment by sync** [comment]
Do you reckon it would be a quite involved task to do. I am keen on trying it. If so where should I start looking

**Comment by sync** [comment]
Ok or is there already :-)

**Comment by cristianoc** [comment]
@sync there's some of it, but happy to let you complete

**Comment by sync** [comment]
yes i just ran the branch and could not see a difference so i think i'll be able to have a play around :-)

**Comment by cristianoc** [comment]
@sync 
Just one more commit. Sent.

**Comment by cristianoc** [comment]
The commit message contains a few TODOs.
https://github.com/cristianoc/genType/pull/254/commits/733a6dbb18581c4a1421b571ffaa8356c5d85ba6

**Comment by sync** [comment]
thank you so mcuh

**Comment by sync** [comment]
Ok will have a look at this first thing in the morning tomorrow (in about 8 hours)

**Comment by sync** [comment]
I am slowly making progress here: https://github.com/cristianoc/genType/pull/255 still have plenty to do :-)

**Comment by cristianoc** [comment]
@sync thanks a lot -- that's great.
I'll make little comments along the way from time to time.

**Comment by sync** [comment]
Please do and also around code style etc... like i not in love with the StringHelper :-(

**Comment by cristianoc** [comment]
Thanks a lot @sync for suggesting the feature, and even implementing a good chunk of it!

**Comment by cristianoc** [comment]
Closing as nearly ready to merge the PR.
