### ISSUE TITLE
If there are both a .re and .rei file warn that gentype annotation is unnecessary in the .re file

### ISSUE THREAD

**Issue by sync** [cristianoc/genType#259]
Got bitten by this the other day where i could not figure out for a bit why gentype wasn't generating anything for my file. And then I wasn't sure if I needed to add a gentype annotation to both of my .re and .rei file.

if there are both a .re and .rei file, genType ignores the .re.
It would be good if it warned you that any annotations in .re are unnecessary.

**Comment by sync** [comment]
Missed this from the documentation

```
### Interface (.rei) and Implementation (.re) files

If both `Foo.rei` and `Foo.re` exist, the annotations are taken from `Foo.rei`.

The behaviour can be overridden by adding annotation `[@genType.ignoreInterface];` at the top of `Foo.rei`. Use case: expose implementation details to JS but not to Reason.

```

**Comment by sync** [comment]
@cristianoc would the warning be emitted into the generated .js or .tsx file like you do for a circular dependency ? 

```
  | CircularC(s, c) =>
    value
    |> EmitText.addComment(
         ~comment=
           "WARNING: circular type "
           ++ s
           ++ ". Only shallow converter applied.",
       )
    |> apply(~config, ~converter=c, ~indent, ~nameGen, ~toJS, ~variantTables)
```

**Comment by cristianoc** [comment]
@sync the issue with emitting in the generated code is that it's not very discoverable.
The upside is that it's very easy to implement.

Ideally, the code should be visible to the IDE too. Not sure though if possible at the moment -- eg if something is emitted on stdout/stderr with a certain format, whether it's picked up from e.g. vscode.
Doing more than printing to stdout/stderr would require collaboration from the compiler, which is not possible at the moment as genType runs as a post-processor.

**Comment by cristianoc** [comment]
Not sure how to generate warnings at the moment.
Would definitely like to explore more once genType is moved inside bucklescript. It will take a little longer for that.
