### ISSUE TITLE
[TypeScript] Consider using ReactNode instead of ReactChild to describe children

### ISSUE THREAD

**Issue by vknez** [cristianoc/genType#265]
Hi,

I'm introducing ReasonML into a large TypeScript React Native application, and I noticed that *genType* defines `children: React.ReactChild` in the `.gen.tsx` file, which does not allow `boolean`, `null`, `undefined`, and `React.Fragment` in place of component child(ren). This prevents me from writing common components in ReasonML. 

From React type definitions:
```typescript
type ReactChild = ReactElement | ReactText;
```
```typescript
type ReactNode = ReactChild | ReactFragment | ReactPortal | boolean | null | undefined;
```

For better interoperability with TypeScript, it seems that `ReactNode` is more appropriate than `ReactChild`. Could you please consider making this change?

#240

**Comment by cristianoc** [comment]
The change is easy to do, just a single line. I’d need to first check the interaction with other things.
Away for 1 week.

**Comment by cristianoc** [comment]
@vknez here's the PR:
https://github.com/cristianoc/genType/pull/266

Let me know if it looks good for your.

**Comment by cristianoc** [comment]
In release 2.41.0.

**Comment by vknez** [comment]
Thanks @cristianoc!

I'll upgrade today/tomorrow, but I'm sure it will work, as I already use a forked `genType`, where I fixed the issue the same way, and it works.
