### ISSUE TITLE
Preparation for genType v3

### ISSUE THREAD

**Issue by ryyppy** [cristianoc/genType#267]
This issue tracks the tasks for the `v3` transition, so we don't forget anything.

## CI for 4.06 & switch to new master
- [x] Copy current `master` to a new branch called `4_02` 
- [x] Merge #100 to make `master` 4.06 by default
- [x] Fix Azure tests on Windows platform (see error below)
- [x] On every tag `v3.*`, upload a new release for every platform to the github releases tab
- [x] Make sure PRs to `4_02` don't trigger builds on Azure

## Appveyor for 4_02
- [x] Ignore all branches but `4_02` (also master)
- [x] Ignore all tags except those starting with `v2.*`
- [x] On every tag `v2.*`, upload a new release to the github releases tab

## CircleCI for 4_02
- [x] Ignore all branches but `4_02` (also master)
- [x] Ignore all tags except those starting with `v2.*`
- [x] On every tag `v2.*`, upload a new release to the github releases tab

## 4_02 Tests
- [x] Add a new commit on `4_02` (Appveyor / CircleCI should build, Azure should not)
- [x] Add a `v2.*` tag to `4_02` and push (Appveyor / CircleCI should build and upload to github, Azure should not)
- [x] Add a new commit on `master` (Azure should build, Appveyor / CircleCI should not)
- [ ] Add a `v3.*` tag to `master` and push (Azure should build and upload to github, Appveyor / CircleCI should not)
- [ ] Do a full npm release (as described in the DEVELOPMENT doc)

## Cleanup
- [ ] Add note on version compatibility (v3 = BuckleScript 6.x) (v2 = BuckleScript 5.x, only bugfixes)
- [ ] Clean up `4_02` branch (remove any 4_06 references completely)
- [ ] Bump version, release `gentype@3` on npm
- [ ] Post release note on twitter, discord, reasonml.chat
- [x] Detect attempts to read .cmt files with wrong format, and suggest configuring bucklescript to a version based on 4.06.

**Error message on Windows:**

```
> gentype@2.41.0 test D:\a\1\s
> node ./scripts/run_integration_tests.js

Check existing binary: D:\a\1\s\_esy\default\build\install\default\bin\gentype.native.exe
Test failed unexpectly: _esy\default\build\install\default\bin\gentype.native.exe does not exist. Use `esy` first!
Error: _esy\default\build\install\default\bin\gentype.native.exe does not exist. Use `esy` first!
    at checkSetup (D:\a\1\s\scripts\run_integration_tests.js:110:11)
    at main (D:\a\1\s\scripts\run_integration_tests.js:142:5)
    at Object.<anonymous> (D:\a\1\s\scripts\run_integration_tests.js:158:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
```

**Comment by cristianoc** [comment]
Declaring this pretty much all done.
