### ISSUE TITLE
Flow libdef for React$Ref is overly restrictive for React.Ref.t

### ISSUE THREAD

**Issue by a7c** [cristianoc/genType#271]
genType translates `React.Ref.t` (which takes an arbitrary type) to `React$Ref` in Flow. But `React$Ref` is defined as follows: 
```
/**
 * The type of the ref prop available on all React components.
 */
declare type React$Ref<ElementType: React$ElementType> =
  | { -current: React$ElementRef<ElementType> | null, ... }
  | ((React$ElementRef<ElementType> | null) => mixed)
  | number | string;
```
where
```
declare type React$ElementType =
  | string
  | React$AbstractComponent<empty, mixed>;
```

It doesn't look like `React$Ref` is the right type to transform `React.Ref.t` to--it only works for cases where the ref is specifically the ref prop for a React component. For reference, the type of `React.createRef` in flow is simply
```
declare export function createRef<T>(
  ): {|current: null | T|};
```

**Comment by cristianoc** [comment]
@a7c see if this does what you need: https://github.com/cristianoc/genType/pull/276.
