### ISSUE TITLE
genType and BuckleScript don't agree on reserved word exports

### ISSUE THREAD

**Issue by rickyvetter** [cristianoc/genType#280]
If you write code like this:

```reason
[@genType]
let window = (a) => a + 1;
```

BuckleScript will output `exports.$$window = $$window`, and genType will import it as `Module.window`. This inconsistency allows for incorrect bindings to JS callers.

[List of reserved words here.](https://github.com/BuckleScript/bucklescript/blame/c7409f4dc59d8949fb3a8d825036a7c16f847fa3/scripts/build_sorted.ml#L25)

Speaking to @tomgasson about this and we are leaning toward saying this should be resolved on the BS side - specifically we don't think exports ever need to be protected in this way. It seems always safe to write:

```js
exports.window = $$window;

// or (assuming this happens at end of file)

export window = $$window;
```
and to import as

```js
var MyModule = require("path");
var $$window = MyModule.window;

// or

import {window as $$window} from "path";
```

cc @bobzhang

**Comment by bobzhang** [comment]
It is indeed better for user experience, but it means we need treat variables in three styles: normal, predefined globals, keywords (previously two) which means more careful thoughts.
Can we have a quick fix for this

**Comment by rickyvetter** [comment]
@bobzhang is it true that we would need three styles? I believe this applies to both predefined globals and keywords/reserved words. See https://stackoverflow.com/questions/41727919/how-to-export-a-variable-which-has-reserved-name-in-es6 for es module usage, and for common JS and nested modules things like `{true: 1}; foo.true = 1;` are valid. Are there situations you could not do this with reserved words?

**Comment by cristianoc** [comment]
@rickyvetter @bobzhang are there any action items on this?
Once decided on which side this should be addressed, happy to progress on it.

**Comment by cristianoc** [comment]
Please reopen if there's more to be done on the genType side.
