### ISSUE TITLE
[@bs.meth] and genType

### ISSUE THREAD

**Issue by wokalski** [cristianoc/genType#295]
For this module:

```reason
module Socket = {
  [@genType]
  type t = {
    .
    [@bs.meth] "on": (string, (. event) => unit) => unit,
    [@bs.set] "binaryType": string,
    [@bs.meth] "send": data => unit,
  };
};
```

gentype generates:

```ts
export type Socket_t = {
  readonly on: Js_Internal_meth<
  | {
    tag: "Arity_2"; 
    value: [string, (_1:Socket_event) => void]
  },void>; 
  binaryType: string; 
  readonly send: Js_Internal_meth<
  | {
    tag: "Arity_1"; 
    value: Socket_data
  },void>
};
```

It's possible to get ~methods~ functions out of this:

```ts
type Method_Arity_X<A> = {
  tag: string;
  value: A;
};

export type Internal_meth<
  T extends Method_Arity_X<any>,
  Ret
> = T extends Method_Arity_X<infer A>
  ? A extends any[]
    ? (...args: A) => Ret
    : (_: A) => Ret
  : never;
```

But I'm not sure if it's correct (shouldn't it be `on(...)` and not `on: (...)`, and what's more it feels like genType should special case it (like [@bs.set]).

**Comment by cristianoc** [comment]
@wokalski definitely not something one would want to write by hand. Also, if bucklescript changes anything, it would be hard to keep it in sync by hand. While genType can do it once for everyone.

I'll look into it.

**Comment by cristianoc** [comment]
Looking into that here: https://github.com/cristianoc/genType/pull/297.

**Comment by cristianoc** [comment]
I think it's done. Will be in the next relase.

**Comment by wokalski** [comment]
@cristianoc thanks! Is it necessary for `bs.meth` with ``` `Arity_2``` to map to a method that gets a single tuple argument instead of a method that accepts two args. I'm afraid it'll make interop with TS quite tedious.

**Comment by cristianoc** [comment]
That was a bit too quick.

**Comment by cristianoc** [comment]
@wokalski  Check master, see if it's good.

**Comment by wokalski** [comment]
It looks great now, thanks!

**Comment by cristianoc** [comment]
Thanks for reporting the issue. Bot times!
