### ISSUE TITLE
CI doesn't do a github release when `npm version` is used on master

### ISSUE THREAD

**Issue by ryyppy** [cristianoc/genType#298]
Just released v3.2.0, even though all the tagging etc. is done correctly, it seems that the check for the SourceBranch doesn't work properly (it seems to see `refs/heads/master` instead of `refs/tags/v3.2.0`:

![image](https://user-images.githubusercontent.com/1121889/68321096-5e5c0b00-00c1-11ea-8f77-eb584eb2951c.png)

Will need to look further into this, maybe it launches two builds, one for the tag and one for the latest commit, but only the last one gets triggered?

**Comment by cristianoc** [comment]
Issues GC, only keeping those blocked on something. We don't need a reminder for this one.

**Comment by cristianoc** [comment]
As it happens, I've just created a release and everything worked.
Not sure what changes.
