### ISSUE TITLE
Generates Functors with type `unknown` (in TS) when they are converted to functions

### ISSUE THREAD

**Issue by gaku-sei** [cristianoc/genType#306]
```reason
module type M = {type t;};

module type SomeFunctor = (M: M) => {let f: M.t => M.t;};

module SomeFunctor: SomeFunctor =
  (M: M) => {
    let f = Obj.magic();
  };

[@genType]
let someFunctor: module SomeFunctor = (module SomeFunctor);
```

Will generated the following output in TS:

```ts
export const someFunctor: unknown = ConstateBS.someFunctor;
```

According to this line: https://github.com/cristianoc/genType/blob/142b35a40476a5d1a39cfec91bc059de5cc71271/examples/flow-react-example/src/FirstClassModules.re#L40 functor to function type generation works when defining args types and returned type explicitly. But it fails when using the shortcut `let someFunctor: module SomeFunctor`.

**Comment by cristianoc** [comment]
@gaku-sei could you give more context on what you want to build?

**Comment by cristianoc** [comment]
Feel free to reopen with more info.
