### ISSUE TITLE
Getntype 3.4.0 broke my builds

### ISSUE THREAD

**Issue by sync** [cristianoc/genType#308]
i get a bunch of errors, had no issues with any of the previous versions:

124/134] Building src/components/Touchable.cmj
Fatal error: exception Sys_error("/github/workspace/packages/my-app/node_modules/re-classnames/lib/bs: No such file or directory")
[125/134] Building src/components/BackIcon.cmj
Fatal error: exception Sys_error("/github/workspace/packages/my-app/node_modules/re-classnames/lib/bs: No such file or directory")
[126/134] Building src/components/CheckinRow.cmj
Fatal error: exception Sys_error("/github/workspace/packages/my-app/node_modules/re-classnames/lib/bs: No such file or directory")
[127/134] Building src/components/StatsView.cmj
Fatal error: exception Sys_error("/github/workspace/packages/my-app/node_modules/re-classnames/lib/bs: No such file or directory")
[128/134] Building src/components/SectionHeader.cmj
Fatal error: exception Sys_error("/github/workspace/packages/my-app/node_modules/re-classnames/lib/bs: No such file or directory")
[129/134] Building src/components/NoteAddedRow.cmj

i use re-classnames

and this is what my component look like:

```js
Css.require("./Touchable.css");

[@react.component]
let make =
    (
      ~testID: option(string)=?,
      ~className=?,
      ~style=?,
      ~onClick=?,
      ~children=?,
    ) => {
  let className =
    Cn.make([
      "hui_touchable",
      "hui_touchable_disabled"->CnUtils.ifNone(onClick),
      className->Cn.unpack,
    ]);

  let handleClick = event => {
    event->ReactEvent.Mouse.preventDefault;

    switch (onClick) {
    | Some(onClick) => onClick(event)
    | None => ()
    };
  };

  let a =
    <a
      ?style
      className
      onTouchStart=ReactEventUtils.noop
      onClick=handleClick
      onKeyDown=ReactEventUtils.noop
      role="button">
      {switch (children) {
       | Some(children) => children
       | None => React.null
       }}
    </a>;

  TestUtils.withTestID(~testID, a);
};

[@gentype]
let default = make;

```

**Comment by sync** [comment]
the error is incorrect because i can cd into `node_modules/re-classnames/lib/bs/`

**Comment by sync** [comment]
i am trying to see if the issue has something to do with re-classname not using bs-platform ^ 6.x

**Comment by sync** [comment]
nothing to do with the bs-platform version it has to do with yarn workspaces

**Comment by sync** [comment]
gentype trying to resolve `node_modules/re-classnames/lib/bs/` to /Users/anthonymittaz/src/homepass-pwa/packages/my-app/node_modules/re-classnames/lib/bs but it's in the root instead

**Comment by sync** [comment]
re-classnames for my setup is located here for example: /Users/anthonymittaz/src/homepass-pwa/node_modules/re-classnames/lib/bs

i can temporarily fix it by trying to hoist it

**Comment by sync** [comment]
yarn has the code int their repo and also here: https://github.com/square/find-yarn-workspace-root/blob/master/index.js

**Comment by Coobaha** [comment]
Should be also related https://github.com/cristianoc/genType/issues/231#issuecomment-553233448

**Comment by sync** [comment]
actually much simpler, it's available if following symlinks, just need to make sure gentype follow symlinks

**Comment by sync** [comment]
@cristianoc i am happy to create a workspace example and give it a shot at fixing the issue, i think I can start from there: https://github.com/cristianoc/genType/blob/c6bcf2778d477c7901b601fe1f740d242d6dc38e/src/ModuleResolver.re#L102

strategy would be to fetch the package.json and merge deps and devDeps and see if  bucklescript dependency is available in the list if not trying recursively go back one folder till the dependency is found... there should be a limit

Wondering if there is a way to detect if in a workspace and also don't want to navigate to too many folders back.

What do you think ?

**Comment by cristianoc** [comment]
@sync, thanks for the report. Let met put the library support under experimental first, by making it opt-in, then look into the search strategy.

**Comment by sync** [comment]
cool, thanks

**Comment by sync** [comment]
and to be honest i think i could just be another config that specify node_modules root, no need for detection, if not we have to worry about so many things :-)

**Comment by cristianoc** [comment]
@sync see https://github.com/cristianoc/genType/releases/tag/v3.4.1.

Now first thing: were you using genType for a dependency? Or did you get a build error anyway?
First, I would want to make sure compilation does not fail, even if the path is wrong.

**Comment by cristianoc** [comment]
Next, I'd like to understand how bucklescript resolved `bs-dependencies`.
The docs are not very specific https://bucklescript.github.io/docs/en/build-configuration#bs-dependencies-bs-dev-dependencies

+ @bobzhang

**Comment by sync** [comment]
No I have no idea why re-classnames is failing gentype I am not using gentype with it. But perhaps it’s trying to guess the type from usage

**Comment by cristianoc** [comment]
First: prevent failure when the path is wrong https://github.com/cristianoc/genType/pull/311.

**Comment by cristianoc** [comment]
Observation: `build.ninja` contains this:
```
g_lib_incls = -I src/location -I src/components -I src/nested -I src -I /Users/cristianoc/reasonml/genType/examples/typescript-react-example/node_modules/reason-react/lib/ocaml -I /Users/cristianoc/reasonml/genType/examples/typescript-react-example/node_modules/somelibrary/lib/ocaml
```

That might be a way to read the path already worked out by bucklescript, but that's brittle.

**Comment by cristianoc** [comment]
@Coobaha also curious if https://github.com/cristianoc/genType/pull/310 solved your issue. So we know that once automated (or not), this will take care of your project.

**Comment by Coobaha** [comment]
@cristianoc I think it won't work for all cases. Some packages might not be hoisted, some might be. So having one root folder setting is not ideal. 

My namespace problem is almost working, it generates incorrect file name, and omits `src` folder (more in my comment in #231)

**Comment by cristianoc** [comment]
@Coobaha good point the info needed is not a single root folder, but the folder will be different for different dependencies.

**Comment by cristianoc** [comment]
The plan is to either get the required info from bucklescript, or copy bucklescript's resolution algorithm.

**Comment by bobzhang** [comment]
@cristianoc actually this metadata is stored somewhere (not documented), will get back to you later

**Comment by bobzhang** [comment]
@cristianoc  check pkgs field in lib/bs/.sourcedirs.json

**Comment by cristianoc** [comment]
@bobzhang thanks found it. That's exactly what is needed.

```
  "pkgs": [
    [
      "bs-platform",
      "/Users/cristianoc/reasonml/genType/examples/typescript-react-example/node_modules/bs-platform"
    ],
    [
      "somelibrary",
      "/Users/cristianoc/reasonml/genType/examples/typescript-react-example/node_modules/somelibrary"
    ],
    [
      "reason-react",
      "/Users/cristianoc/reasonml/genType/examples/typescript-react-example/node_modules/reason-react"
    ]
  ],
```

**Comment by cristianoc** [comment]
@Coobaha: the PR https://github.com/cristianoc/genType/pull/312 now reads the path correctly from `lib/bs/.sourcedirs.json`.

There are a few more things to look at for your `gentype-monorepo-issue`, specifically the business with `"@demo/some-package"` and the magic that creates `DemoSomePackage` out of it.

Would you clean up the `gentype-monorepo-issue` by opting into `"use-bs-dependencies": true,` in `"gentypeconfig"`, and remove all the shims stuff?

**Comment by sync** [comment]
@cristianoc just tested latest master with "use-bs-dependencies": true and it is no longer failing the build thank you .

**Comment by cristianoc** [comment]
@Coobaha I have extracted the remaining issue of scoped package names here: https://github.com/cristianoc/genType/pull/313.

So I think I have a full repro now and don't need `gentype-monorepo-issue` for testing.

**Comment by cristianoc** [comment]
@Coobaha looks like https://github.com/cristianoc/genType/pull/313 has progressed enough that `gentype-monorepo-issue` is supported now (after opting it via `"use-bs-dependencies": true`).

Now waiting for a spec for bucklescript's namespace support, to assess the full extent of what's needed.

**Comment by Coobaha** [comment]
Great! Will test try it out next week when i will reach my laptop

**Comment by cristianoc** [comment]
@Coobaha fantastic. Thanks a lot for the amazing help in isolating the various aspects in need of fixes.

**Comment by cristianoc** [comment]
This is now in release https://github.com/cristianoc/genType/releases/tag/v3.4.2.

**Comment by sync** [comment]
thanks will close this issue 🎆

**Comment by sync** [comment]
tested release with and without `"use-bs-dependencies": true` and it's no longer an issue
