### ISSUE TITLE
Using keywords in record fields when using bs-platfrom@7

### ISSUE THREAD

**Issue by meafmira** [cristianoc/genType#319]
Example:
```reason
[@genType]
type myRec = {
  [@genType.as "type"] type_: string
};

[@genType]
let myVal = {
  type_: "foo"
}
```
will be converted to:
```js
export type myRec = {| +type: string |};

export const myVal: myRec = testBS.myVal;
```

but really testBS.myVal = `{ type_: "foo" }`

**Comment by cristianoc** [comment]
@meafmira thanks for the report.
Indeed, with `@genType.as` a conversion should be performed.
Which itself is not desirable, but at least correct.

Perhaps at some point bucklescript should activate for record fields the same mangling convention used for object fields. + @bobzhang

**Comment by cristianoc** [comment]
Done here: https://github.com/cristianoc/genType/pull/316.

**Comment by meafmira** [comment]
It's awesome! Thank you!

**Comment by cristianoc** [comment]
In release 3.4.3.

**Comment by cristianoc** [comment]
@meafmira FYI see upcoming: https://github.com/cristianoc/genType/pull/323.
