### ISSUE TITLE
Emit PropTypes code for "untyped" language

### ISSUE THREAD

**Issue by ryyppy** [cristianoc/genType#32]
I just realized it would be really great if we could emit actual PropTypes code, as stated in the [React documentation](https://reactjs.org/docs/typechecking-with-proptypes.html).

Since interoping with ReasonReact components in JavaScript land doesn't have any static type checking, it would be great to have at least accurate runtime warnings.

Although this would force the user to use the PropTypes package, I think it's a nice enforcement for good practise.

**Comment by cem2ran** [comment]
Could be interesting to try out the following two projects, and then I guess you could enable and disable proptypes by toggling the babel plugin:

- https://github.com/brigand/babel-plugin-flow-react-proptypes
- https://github.com/atlassian/babel-plugin-react-flow-props-to-prop-types

**Comment by ryyppy** [comment]
I'll close this one, since it's kinda out-of-scope

**Comment by tmattio** [comment]
@ryyppy Why is it out of scope?

I would find this feature really useful :)

My use case is: I use Storybook as a component explorer. With a plugin, it is able to generate some documentation of my React components from the propTypes. So generating the propTypes would allow me to have free documentation for all my components!

**Comment by cristianoc** [comment]
@tmattio here's a first iteration towards emitting prop types:
  https://github.com/cristianoc/genType/pull/177

**Comment by cristianoc** [comment]
Added as opt-in experimental feature:
https://github.com/cristianoc/genType/commit/099b403365fff62740fef5545b5403a702cfbad7
