### ISSUE TITLE
Reference source file in comment

### ISSUE THREAD

**Issue by rickyvetter** [cristianoc/genType#330]
For folks new to Reason it may not be clear which files are responsible for the contents of a .gen.js file. Is there a way to reference the source file in the contents of the new file? Either via string replacement in the fileHeader field or just directly by genType?

**Comment by cristianoc** [comment]
@rickyvetter see https://github.com/cristianoc/genType/pull/331 -- let me have comments on the prasing.

**Comment by rickyvetter** [comment]
Yeah I think the format is good!
