### ISSUE TITLE
Generate files into the same folders as bucklescript

### ISSUE THREAD

**Issue by TomiS** [cristianoc/genType#333]
Hi.

At the moment, bucklescript seems to generate files into `./lib/js/...` folder by default, which is nice because that way the generated files do not "pollute" the actual source code folder.

However, I cannot find a way to force the files generated by gentype to go into the same folder. Instead they stay next to `.re` files. Is there a way to do that? I doubt there is. Should there be? But of course there should, right? :)

**Comment by cristianoc** [comment]
https://github.com/cristianoc/genType#limitations

**Comment by TomiS** [comment]
@cristianoc Ah, sorry, I missed that. May I ask if there is a technical reason for this or is it just about that it hasn't been a priority?

**Comment by cristianoc** [comment]
Cant remember exactly. Certainly introduces more complexity.
There has been no demand for that.
One observation is that at some point the plan is to move genType entirely inside bucklescript, and generate a single file with type annotations. Then by definition the generated types will be wherever the .bs.js files are.

**Comment by TomiS** [comment]
Ok, thanks. Nice to hear about the future plans. I'm closing this then.
