### ISSUE TITLE
Invalid imports generated for transitive dependet projects.

### ISSUE THREAD

**Issue by Coobaha** [cristianoc/genType#336]
Please clone this repo to reproduce: https://github.com/Coobaha/gentype-transitive-deps

issue:
- `packageA` is `bs-dependency` of `root` package.
- `packageA` is using `subpackageB` as `bs-dependency`
- building `root` outputs invalid TS code for `packageA`
    ```
    import {Demo_myint as SubpackageB_Demo_myint} from './SubpackageB.gen';
    ```
   instead of 
    ```
    import {Demo_myint as SubpackageB_Demo_myint} from 'subpackageB/Demo.gen';
    ```

**Comment by cristianoc** [comment]
@Coobaha after build, the `lib/bs/.sourcedirs.json` file is:

```
{
  "dirs": ["src"],
  "pkgs": [
    [
      "gentype",
      "/Users/cristianoc/reasonml/gentype-transitive-deps/node_modules/gentype"
    ],
    [
      "bs-platform",
      "/Users/cristianoc/reasonml/gentype-transitive-deps/node_modules/bs-platform"
    ],
    [
      "packageA",
      "/Users/cristianoc/reasonml/gentype-transitive-deps/node_modules/packageA"
    ]
  ],
  "generated": []
}
```

So it looks like bucklescript does not generate any info for transitively dependent projects.

**Comment by cristianoc** [comment]
@Coobaha could you open an issue in the bucklescript project?

**Comment by Coobaha** [comment]
done 👍

**Comment by cristianoc** [comment]
Moved to bs.
