### ISSUE TITLE
Is there a roadmap for a potential integration upstream with BuckleScript?

### ISSUE THREAD

**Issue by jchavarri** [cristianoc/genType#34]
Thanks for genFlow!!! It's really amazing ✨ 

I am wondering if there are any plans for an integration of genFlow / genType upstream with BuckleScript? That would simplify most of the setup / configuration, as it could become just another bsconfig.json option. cc @bobzhang 

I have also noticed that `re.js` files are not updated after compiling, and genFlow users are forced to call `bsb -clean-world` and then `bsb -make-world` again, or clean the `.re.js` files in some other way before re-compiling. Not sure if this is something that could also go away if genFlow was integrated with BuckleScript?

In case there is a list of features or additions that need to happen before this potential integration, how would that list look like? Maybe making it public would enable more people to jump onboard and help with the project :)

Thanks again for all your great work!!

**Comment by cristianoc** [comment]
Yes there are plans to integrate with bucklescript so there won’t be any installation instructions.

About build issues, does it happen in watch mode too?

**Comment by jchavarri** [comment]
> Yes there are plans to integrate with bucklescript so there won’t be any installation instructions.

Looking forward to this! :)

> About build issues, does it happen in watch mode too?

No, in watch mode everything seems to work correctly: the `.re.js` files get updated. Maybe BuckleScript ignores the post-processed files if they exist already under the normal build process?
