### ISSUE TITLE
Unused type declaration in typescript

### ISSUE THREAD

**Issue by hamza0867** [cristianoc/genType#341]
Hi  
I am using genType to auto-generate typescript bindings and I noticed that some type declarations in the `.gen.tsx` files are unused. For example given the following `Index.rei` file:  
```ocaml
module BgPrimaryReason: {
  [@genType]
  [@react.component]
  let make: (~text: string) => ReasonReact.reactElement;
};
```
I get the correspnding `Index.gen.tsx` file like so:
```typescript
/* TypeScript file generated from Index.rei by genType. */
/* eslint-disable import/first */


// tslint:disable-next-line:no-var-requires
const IndexBS = require('./Index.bs');

// tslint:disable-next-line:interface-over-type-literal
export type Props = { readonly text: string };

export const BgPrimaryReason_make: React.ComponentType<{ readonly text: string }> = IndexBS.BgPrimaryReason.make;

export const BgPrimaryReason: { make: React.ComponentType<{ readonly text: string }> } = IndexBS.BgPrimaryReason
```
As you can see the `type Props = { readonly text: string };` is not used anywhere, where it should actually be used to type the `React.ComponentType` like so `React.ComponentType<Props>`

Is this happening for a reason (no pun intended) or is it actually a bug ?

Thank you so much for this great product

**Comment by cristianoc** [comment]
@hamza0867 I’ve now remembered. The type Props was used in the generated code in the past, then had to be inlined for technical reasons.
I left it in case client code wants to write e.g.: this value has type: “the type of the props of that component”.
It’s kind of niche I guess, though it does not cost anything. If I knew nobody uses that I might remove it.

**Comment by hamza0867** [comment]
Ok makes sense. Thank you
