### ISSUE TITLE
Add "import React from 'react'" statement to tsx files

### ISSUE THREAD

**Issue by hamza0867** [cristianoc/genType#342]
Hi,

I would love if the generated `.tsx` files would import React so that other libraries could take advantage of the exported types from "@types/react".  

My specific use case is the integration of the tsx files with the documentation site generator [docz](https://www.docz.site/), specifically the [Props component](https://www.docz.site/docs/built-in-components#component-props). Where all it needs is the component definition to generate the documentation for the props of a react component. But it needs React to be imported in the tsx file ( which makes sense to me )

Here is what the docs look like when there is no `import React from "react"` statement in the generated `.tsx` files.

![Screenshot from 2019-12-23 13-30-14](https://user-images.githubusercontent.com/38878982/71358184-6a742d00-2588-11ea-9b18-b87c4ffd365c.png)

Here is what the docs look like when there is an import statement of React in the generated `.tsx` files:

![Screenshot from 2019-12-23 13-33-11](https://user-images.githubusercontent.com/38878982/71358373-fede8f80-2588-11ea-9892-95f44864bc14.png)

I think the relevant line of code to change is [this one](https://github.com/cristianoc/genType/blob/master/src/Config_.re#L57)

Thank you so much

**Comment by cristianoc** [comment]
@hamza0867 I would rather not emit an import for react on *all* the `.tsx` files.
As a first step: https://github.com/cristianoc/genType/pull/343
It only emits the import if the file exports one function component.
What's the full extent of your use case?

**Comment by hamza0867** [comment]
@cristianoc I believe that's all I need to make it work. I just need the `.tsx` files who use React type annotations to import react. There is another small tweak that I would love to have is to annotate react components with `React.FunctionComponent` instead of `React.ComponentType` but that is something that I will have to do on my own ( since it doesn't make sense to have all components be function components especially for backwards compatibility ).

**Comment by hamza0867** [comment]
Ok so I just changed the module resolution in tsconfig so I don't need the change from `React.ComponentType` to `React.FunctionType`.  
All I need is for genType to import React in files where React is used.

Thank you so much

**Comment by cristianoc** [comment]
@hamza0867 creating release 3.9.0 now.

**Comment by hamza0867** [comment]
Thank you so much

**Comment by cristianoc** [comment]
@hamza0867 if this is for your attempt to publish TS libraries, would you write a few words on the outstanding blocks you have found?
I can only guess doc generation expects TS code to be in a specific format, though it would be interesting to confirm what that is.

**Comment by hamza0867** [comment]
@cristianoc Sorry for the late response. I will be setting a repository where I put everything that I found and the main blockers that I encountered ( and still encountering )
