### ISSUE TITLE
Investigate support for docz with TypeScript.

### ISSUE THREAD

**Issue by cristianoc** [cristianoc/genType#345]
See example by @hamza0867:
https://github.com/hamza0867/docz-reason

**Comment by cristianoc** [comment]
@hamza0867 how does one run docz on the example?
And what’s the meaning of “does not work” in the comments? It refuses to run or gives the wrong output?

**Comment by hamza0867** [comment]
@cristianoc Sorryu for the late answer.  
You run the docz by using the command `yarn dev` then search for the component `Alert` in the search menu, and click on `Alert`. 

Does not work means docz doesn't parse the props of the component correctly.

**Comment by cristianoc** [comment]
@hamza0867 I've deleted `Alert.bs.d.ts` and `yarn dev` still appears to work unless I'm missing something. Could you verify, if that's true?

**Comment by hamza0867** [comment]
@cristianoc It is indeed working. I must've missed it. Good catch.

**Comment by hamza0867** [comment]
@cristianoc I updated the repo with updated comments and added the case of a default import.

**Comment by cristianoc** [comment]
@hamza0867 as a second change: I believe using `import` instead of `required` is not necessary -- in fact it breaks TS compilation (once `Alert.bs.d.ts` is removed).

**Comment by hamza0867** [comment]
@cristianoc Yes that is also true. I guess that means that the only problem is with the naming of the component. Right ?? 
I don't know how I missed all of these things.

**Comment by hamza0867** [comment]
@cristianoc I updated the repo with more accurate comments. I also made comments about the type used to type components ( `ComponentType` vs `FC / FunctionComponent / ClassComponent` )

**Comment by cristianoc** [comment]
@hamza0867 change number 3:
rebuild `Alert.bs.js` using the compiler, and change `Alert.tsx` to use:
```
export const Alert: FC<{ readonly text: string }> = AlertBS.make;
```

Just peeling off all the non-essential layers one by one, until we get to a minimum of required changes.

**Comment by hamza0867** [comment]
@cristianoc I just tried the changed you mentioned

> @hamza0867 change number 3:
> rebuild `Alert.bs.js` using the compiler, and change `Alert.tsx` to use:
> 
> ```
> export const Alert: FC<{ readonly text: string }> = AlertBS.make;
> ```
> 
> Just peeling off all the non-essential layers one by one, until we get to a minimum of required changes.
@hamza0867 change number 3:
rebuild `Alert.bs.js` using the compiler, and change `Alert.tsx` to use:


I just tried this change and the props parsing breaks again. Is it working on your side ??

![Screenshot from 2020-01-07 10-18-54](https://user-images.githubusercontent.com/38878982/71883670-2dd33480-3137-11ea-8ca6-61064af5fecf.png)

![Screenshot from 2020-01-07 10-17-33](https://user-images.githubusercontent.com/38878982/71883567-fb293c00-3136-11ea-910f-0d99eb88d5b6.png)

**Comment by cristianoc** [comment]
@hamza0867 thanks that's right -- did not notice that.

**Comment by cristianoc** [comment]
@hamza0867 looks like docz is fragile. For example, it works with this in `Alert.bs.js`:
```js
export {
  make,
  Alert
};
```

but not with this:
```js
export {
  Alert,
  make
};
```

One workaround is to wrap the function:
```ts
export const Alert: FC<{ readonly text: string }> = function Alert(Props) { return AlertBS.make(Props) };
```

Though that has a bunch of consequence. Extra allocation for sure, and more importantly the loss of function identity. So it kills memoization.

One could go along those lines to work around docz and get some special suboptimal mode. Though before doing that, I would suggest to investigate whether it's possible to open issues in docz to remove the limitations to begin with.

**Comment by hamza0867** [comment]
@cristianoc I totally agree. Maybe it is time to open issues in docz. Thank you so much for sticking with me through this

**Comment by cristianoc** [comment]
This might become relevant over time:
https://devblogs.microsoft.com/typescript/announcing-typescript-3-8-beta/#type-only-imports-exports

**Comment by cristianoc** [comment]
This went a little quite. To be reopened later to continue the convo.
