### ISSUE TITLE
Issue with genType.as and generics in TypeScript.

### ISSUE THREAD

**Issue by parkerziegler** [cristianoc/genType#347]
Thanks so much for the awesome library @cristianoc, truly a great piece of engineering!

I noticed that `genType` seems to struggle a bit when using `[@genType.as]` on a `type` that, in Reason, takes a type parameter and when converted to TypeScript should be a generic.

For example, if I do:

```reason
[@genType.as "Vector"]
type vector('a) = ('a, 'a);
```

I expect to get:

```typescript
export type Vector<A> = [A, A];
```

But instead, I get:

```typescript
export type vector<a> = [a, a];
export type Vector = vector;
```

Along with the error: `Generic type 'vector' requires 1 type argument(s).` on that second line. The generic is not actually getting bubbled up to the renaming.

I may just be missing some piece of documentation around how to properly do this. I did also try:

```reason
[@genType.as "Vector<A>"]
type vector('a) = ('a, 'a);
```

But this still doesn't quite work:

```typescript
export type vector<a> = [a, a];
// A doesn't get passed on to vector
export type Vector<A> = vector;
```

Thanks again so much for a great lib, this is just a minor thing I noticed 🤗

**Comment by cristianoc** [comment]
@parkerziegler thanks for the report!
Indeed type parameters were missing. Done here: https://github.com/cristianoc/genType/pull/348.

**Comment by parkerziegler** [comment]
❤️ thanks so much!

**Comment by cristianoc** [comment]
In release 3.10.0 being created right now.
