### ISSUE TITLE
Array of multiple type returned from external function TS function type errors in generated code.

### ISSUE THREAD

**Issue by MarcelCutts** [cristianoc/genType#349]
Hello!

I have run into an issue with importing a certain kind of genType import - one that returns an array of mixed types. 

Example

```ts
// returnMixedArray.ts
export const returnMixedArray = () => ["string", true];
```

```re
// ReturnMixedArrayImport.re
[@genType.import ("./returnMixedArray", "returnMixedArray")]
external returnMixedArray: unit => (string, bool) = "";
```

```ts
// ReturnMixedArrayImport.gen
import {returnMixedArray as returnMixedArrayNotChecked} from './returnMixedArray';

// In case of type error, check the type of 'returnMixedArray' in 'ReturnMixedArrayImport.re' and './returnMixedArray'.
export const returnMixedArrayTypeChecked: (_1:void) => [string, boolean] = returnMixedArrayNotChecked;

// Export 'returnMixedArray' early to allow circular import from the '.bs.js' file.
export const returnMixedArray: unknown = returnMixedArrayTypeChecked as (_1:void) => [string, boolean];

/* ERROR
const returnMixedArrayTypeChecked: (_1: void) => [string, boolean]
Type '() => (string | boolean)[]' is not assignable to type '(_1: void) => [string, boolean]'.
  Type '(string | boolean)[]' is missing the following properties from type '[string, boolean]': 0, 1ts(2322)
*/

```

My interpretation of this error is that it expects to match against a definition for an array of union types, which is not what I'm trying to express, unfortunately.

I can otherwise bind and call this function normally if I opt out of using genType.

e.g.

```
[@bs.module "./returnMixedArray"]
external returnMixedArray: unit => (string, bool) = "returnMixedArray";

Js.log(returnMixedArray());

// node output: [ 'string', true ]
```

It does seem to work fine with arrays as long as they're of undetermined length and homogenous types, but this won't be suitable for the example given above.

Thank you for all your hard work!

**Comment by cristianoc** [comment]
@MarcelCutts there's no Reason type corresponding to TS's `string | bool`.
The code above attempts to use `(string, bool)` which is a tuple.

**Comment by cristianoc** [comment]
Nothing special about arrays.

**Comment by MarcelCutts** [comment]
Sure, I think I understand that statement. I guess my followup is - how should one describe this kind of function in the `external ...` state such that genType is happy about it?

```re
[@genType.import ("./returnMixedArray", "returnMixedArray")]
external returnMixedArray: unit => <whatGoesHere?> = "";
```

**Comment by cristianoc** [comment]
Not much to do in a typesafe way.
E.g. you could import numberOrString as an opaque type:
https://github.com/cristianoc/genType/commits/master

Though then you can't do anything with it. If you want to do case analysis some conversion is needed. Either on the JS or Reason side. E.g. to type `| S(string) | I(int)`.

**Comment by cristianoc** [comment]
Gentype will do the conversion for you if you declare
```reason
type t = | S(string) | I(int);
```
but then extra work needs to be done on the JS side to construct appropriate values of TS type:
```ts
    { tag: "I"; value: number }
  | { tag: "S"; value: string };
```

**Comment by MarcelCutts** [comment]
Those are some nice pragmatic solutions. I think we can progress our imported react hooks from here with a bit more confidence.

Thank you very much for your insights as always!
