### ISSUE TITLE
Mismatch between .bs.js and .re.js when adding [@genType] to a shadowed variable

### ISSUE THREAD

**Issue by a7c** [cristianoc/genType#354]
Suppose we have the following `Module.re`:
```
[@genType]
let test = (~test) => Js.log(test);

let test = () => test(~test="test");
```

genType would generate types for the first `test` in `Module.re.js`, since the annotation was applied there:
```
const test: <T1>({| +test: T1 |}) => void = function <T1>(Arg1: $any) {
  const result = ModuleBS.test(Arg1.test);
  return result
};;
exports.test = test
```

But the implementation in `Module.bs.js` would be for the second `test`:
```
function test(param) {
  console.log("test");
  return /* () */0;
}
```

**Comment by cristianoc** [comment]
@a7c to double check: in this case nothing would be exported right?
There's also the issue that if both are annotated, then 2 values with the same name are exported, which is also an error.
