### ISSUE TITLE
Emitting doc comments in generated code?

### ISSUE THREAD

**Issue by Schmavery** [cristianoc/genType#355]
Hi, thanks for the library, it works great! Some questions about the usability of the generated typescript file, related to the usecases in https://github.com/cristianoc/genType/issues/95. The genType-generated code is really good, but we're looking into what we can do to improve the in-editor experiences for typescript users using a genType-ed reason library.

I was wondering if there is any support for emitting doc comments on reason functions in the generated typescript code? Then I could write my doc comments in reason using the tsdoc format and the users of the generated library could have docs info in their editor, for example.

Relatedly, it seems like all the argument names in the generated TS code are `_1`, `_2` etc, rather than the names in the ocaml/reason code. Is there a technical reason why we can't get the original argument names or is it just a matter of not having the time to get around to it yet?

It would be amazing if we could figure out how to get a result something like this, for example:
Reason:
```reason
/**
  * Returns the average of two numbers.
  *
  * @param message - A message to be signed
  * @param key - The keypair with which to sign the message 
  * @returns A signed message
 */
[@genType]
let signMessage =
  (. message: string, key: key) => {
    ...
  };
```
Typescript:
```typescript
/**
  * Returns the average of two numbers.
  *
  * @param message - A message to be signed
  * @param key - The keypair with which to sign the message 
  * @returns A signed message
 */
export const signMessage: (message:string, key:key) => signed<string> = CodaClientSDKBS.signMessage;
```

How hard would a change like this be, do you think? Is it something that would make sense for this tool?

**Comment by cristianoc** [comment]
@Schmavery that's a nice idea. Doc comments are represented as attributes, so they can just be extracted and printed.
For the name of arguments, I half remember there were some issues with type checking on the TS side. Worth revisiting to see what can be done. E.g. it might be that the issues were for importing and not exporting, and something can be done there.

**Comment by cristianoc** [comment]
@Schmavery here's initial support: https://github.com/cristianoc/genType/commit/82ac45bf3dca8ee4251828d6a179c751c02c6e52.

It looks like the name of the arguments is stripped in the AST, so there's no way for genType to recover it, unless labeled arguments are used.
The upcoming bs support for uncurried labeled args could help for at least that use case, when ready.

**Comment by cristianoc** [comment]
Actually, it's possible to apply best-effort to extract the argument names from the expression used to define the function in the AST. This covers a bunch of cases.

**Comment by cristianoc** [comment]
Here's a complete PR: https://github.com/cristianoc/genType/pull/360.

@Schmavery let me know if it does everything required to improve the in-editor experience.

**Comment by Schmavery** [comment]
That PR looks amazing, thanks for such a quick turnaround!
I just tried it out and it looks great. The only thing I can see that's still a little funny is that functions that take no arguments are marked as (for example):
```typescript
const genKeys: (param: void) => t
```
instead of 
```typescript
const genKeys: () => t
```
That said, it's not a big deal, and I'd love to use #360 as-is, so no need to address it now.

**Comment by Schmavery** [comment]
I managed to fiddle with EmitType.re so that it would specially handle a list of arguments that contained only 1 unit, not sure if it will cause any other issues but in case it helps...

```diff
diff --git a/src/EmitType.re b/src/EmitType.re
index 5c20eb3..396d91e 100644
--- a/src/EmitType.re
+++ b/src/EmitType.re
@@ -390,30 +390,36 @@ and renderFunType =
   (inFunType ? "(" : "")
   ++ EmitText.genericsString(~typeVars)
   ++ "("
-  ++ String.concat(
-       ", ",
-       List.mapi(
-         (i, {argName, type_}) => {
-           let parameterName =
-             if (config.language == Flow) {
-               "";
-             } else {
-               (argName == "" ? "_" ++ string_of_int(i + 1) : argName) ++ ":";
-             };
-           parameterName
-           ++ (
-             type_
-             |> renderType(
-                  ~config,
-                  ~indent,
-                  ~typeNameIsInterface,
-                  ~inFunType=true,
-                )
-           );
-         },
-         argTypes,
-       ),
-     )
+  ++ (
+    switch (argTypes) {
+    | [{argName, type_: Ident({builtin: true, typeArgs: [], name: "void"})}] => ""
+    | argTypes =>
+      String.concat(
+        ", ",
+        List.mapi(
+          (i, {argName, type_}) => {
+            let parameterName =
+              if (config.language == Flow) {
+                "";
+              } else {
+                (argName == "" ? "_" ++ string_of_int(i + 1) : argName) ++ ":";
+              };
+            parameterName
+            ++ (
+              type_
+              |> renderType(
+                   ~config,
+                   ~indent,
+                   ~typeNameIsInterface,
+                   ~inFunType=true,
+                 )
+            );
+          },
+          argTypes,
+        ),
+      )
+    }
+  )
   ++ ") => "
   ++ (
     retType |> renderType(~config, ~indent, ~typeNameIsInterface, ~inFunType)

```

**Comment by cristianoc** [comment]
@Schmavery good catch! There's an issue if the return type requires conversion, as the generated code would be ill-typed.
But, the same change can be applied much earlier, so the conversion function does not try to use a non-existing argument. Coming next.

**Comment by cristianoc** [comment]
Updated PR.

**Comment by Schmavery** [comment]
Your updated PR works on my code, thanks! Feel free to merge whenever is convenient for you :)

**Comment by cristianoc** [comment]
@Schmavery in release 3.12.0: https://github.com/cristianoc/genType/releases/tag/v3.12.0.
