### ISSUE TITLE
Object unions

### ISSUE THREAD

**Issue by TomiS** [cristianoc/genType#390]
Hey, is it currently possible to have any kind of Reason code that would cause genType to output something like this (in flow):
```js
// @flow
type text = {
  type: 'text',
  value: string,
  fontSize: number,
};
type icon = {
  type: 'icon',
  path: string,
};
type union = text | icon;
// flow can refine the type
const print = (content: union) => {
  if (content.type === 'text') {
    console.log(content.value);
  }
  if (content.type === 'icon') {
    console.log(content.path);  
  }
} 
```

I'm aware of the current behavior of converting variants to objects with a `tag` and `value`. It's nice if one can control the Js side implementation, but problematic if one cannot.

**Comment by cristianoc** [comment]
@TomiS any Reason type that maps to `text | icon` would require custom case analysis on the Reason side, and the case analysis would not be expressible directly in Reason.
What one could do instead is to keep the type abstract in Reason, and share the responsibilities between Reason and JS, as in e.g.:

```reason
[@genType.import "./TheJsFile"]
type union;

type text = {
  type_: string,
  value: string,
  fontSize: int,
};

type icon = {
  type_: string,
  path: string,
};

[@genType.import "./TheJsFile"]
external getText : union => option(text) = "getText";

[@genType.import "./TheJsFile"]
external getIcon : union => option(icon) = "getIcon";
```

The implementation of `getTest` and `getIcon` would then be doen in JS, which knows about the union type.

**Comment by TomiS** [comment]
Thank for help! Closing.
