### ISSUE TITLE
Is there a way to generate `.ts` files if you are not using react?

### ISSUE THREAD

**Issue by idkjs** [cristianoc/genType#398]
Is there a way to generate `.ts` files if you are not using react?

Seems like we can only generate `.tsx`. If you wanted to use [src/MyMath.ts](https://github.com/cristianoc/genType/blob/master/examples/typescript-react-example/src/MyMath.ts) without bring in `jsx` into `tsconfig.json`, is that possible? 

Trying it now throughs a typescript compiler error.

Thanks.

**Comment by cristianoc** [comment]
@idkjs what's the impact of bringing `jsx` into `tsconfig.json`? I was assuming it would be a feature built into TS. What's the difference in practice?

**Comment by cristianoc** [comment]
As far as I know `.ts` and `.tsx` files can use one another without problems. But maybe there's something else.

**Comment by idkjs** [comment]
I am going to reproduce and get back to you. Happened last week. Standby.

**Comment by idkjs** [comment]
So you are correct. Problem was me not understanding that we could use `.tsx` files as simple non-react `.js` files where are are not using react. Here is the reproduction:https://github.com/idkjs/gentype-ts-classes.

The problem I am coming up against is how to instantiate an `AbsoluteValue.t` object.

In `.ts` I am able to do it like this:
```ts
let abs = new AbsoluteValue();
console.log("abs: ", abs);
console.log("abs.prop: ", abs.prop);

abs.prop = 1.1;
console.log("abs.prop: ", abs.prop);

console.log("abs.getProp: ", abs.getProp());
```

Which outputs:
```sh
abs:  AbsoluteValue {}
abs.prop:  undefined
abs.prop:  1.1
abs.getProp:  1.1
```

How would I do it on the reason side?

Should i open a new issue for this?

**Comment by cristianoc** [comment]
@idkjs indeed classes are the main kind of values that does no really have a 1to1 correspondence in Reason. So it seems that initialization is best done on the JS side, but the initialization function can then be imported into Reason.
Essentially the class will be encapsulated as a functional API that Reason (or other TS code) can then use.

Let me know if this makes sense, and happy to follow on in a different issue if needed.

**Comment by idkjs** [comment]
So back to the original issue. In this repro: https://github.com/idkjs/reason-ts-classes-gentype/blob/master/src/UseJsValue.re

I am trying to access 
```
[@genType.import "./MyMath"] external default: int = "default";
```

with this [line](https://github.com/idkjs/reason-ts-classes-gentype/blob/a171df9abaeeff40375613d426501bd79a90a1d5/src/UseJsValue.re#L13-L14):

```reason
let default = ImportJsValue.default;
Js.log2("default: ", default);
```
## Expected outcome

`34` logs to console.

## Actual outcome

Running `node src/UseJsValue.bs.js` i get the following error:`Error: Cannot find module './ImportJsValue.gen'`:

```sh
~/D/reason-ts-classes-gentype ❯❯❯ node src/UseJsValue.bs.js
internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module './ImportJsValue.gen'
Require stack:
- /Users/mandalarian/Downloads/reason-ts-classes-gentype/src/ImportJsValue.bs.js
- /Users/mandalarian/Downloads/reason-ts-classes-gentype/src/UseJsValue.bs.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/mandalarian/Downloads/reason-ts-classes-gentype/src/ImportJsValue.bs.js:4:24)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/mandalarian/Downloads/reason-ts-classes-gentype/src/ImportJsValue.bs.js',
    '/Users/mandalarian/Downloads/reason-ts-classes-gentype/src/UseJsValue.bs.js'
  ]
}
```
The file is there:

```sh
~/D/reason-ts-classes-gentype ❯❯❯ tree src

src
├── DemoTS.js
├── DemoTS.js.map
├── DemoTS.ts
├── ImportJsValue.bs.js <------
├── ImportJsValue.gen.js
├── ImportJsValue.gen.js.map
├── ImportJsValue.gen.jsx
├── ImportJsValue.gen.jsx.map
├── ImportJsValue.gen.tsx
├── ImportJsValue.re
├── MyMath.js
├── MyMath.js.map
├── MyMath.ts
├── UseJsValue.bs.js
├── UseJsValue.gen.js
├── UseJsValue.gen.js.map
├── UseJsValue.gen.jsx
├── UseJsValue.gen.jsx.map
├── UseJsValue.gen.tsx
└── UseJsValue.re

0 directories, 20 files
~/D/reason-ts-classes-gentype ❯❯❯ 
```

What am I missing here?

**Comment by cristianoc** [comment]
@idkjs I've checked out your repo and:
```
yarn build
npx tsc --jsx preserve
```

On Mac.
Is the error in master?

**Comment by cristianoc** [comment]
Looks like `src/ImportJsValue.gen.js` is not checked in btw.

**Comment by idkjs** [comment]
Updated master with `jsx:preserve` set in `tsconfig.json`

This is my console:
<img width="978" alt="Screen Shot 2020-03-26 at 12 44 31 PM" src="https://user-images.githubusercontent.com/2370391/77672806-b8ba1300-6f5f-11ea-9740-6d03f3eff48c.png">

Current error appears to reference [var CreateBucklescriptBlock = require('bs-platform/lib/es6/block.js');](https://github.com/idkjs/reason-ts-classes-gentype/blob/24cf3952c9a33b36414c4622b0986e644f84aa48/src/ImportJsValue.gen.js#L18):

```sh
~/D/reason-ts-classes-gentype ❯❯❯ node s
rc/UseJsValue.bs.js
/Users/mandalarian/Downloads/reason-ts-classes-gentype/node_modules/bs-platform/lib/es6/block.js:9
export {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1063:16)
    at Module._compile (internal/modules/cjs/loader.js:1111:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/mandalarian/Downloads/reason-ts-classes-gentype/src/ImportJsValue.gen.js:18:31)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
~/D/reason-ts-classes-gentype ❯❯❯ 
```

**Comment by cristianoc** [comment]
This is not related to genType. I suggest you clone an existing working project, and proceed in small steps from there, see where it breaks, then make a small repro.
The error above will happen on any compiled file if invoked in that way.
Closing for now.
