### ISSUE TITLE
Rename to genType

### ISSUE THREAD

**Issue by cristianoc** [cristianoc/genType#40]
Gradually rename the project to genType, with small extensions followed by one breaking change.

**Comment by cristianoc** [comment]
This allows to use gentypeconfig.json:
https://github.com/cristianoc/genFlow/commit/8a8250d4e39bf6c5549a8fc016de098bd16239b6

**Comment by nikgraf** [comment]
ohh nice, so one tool to generate multiple targets?

**Comment by tutturen** [comment]
I would love a tool that generates types for Flow, TypeScript and vanilla JS in one go. That would make it a joy to write js libraries in Reason.

**Comment by cristianoc** [comment]
@tutturen that’s definitely doable. The Flow and TS generated code is different, but we already have 2 extensions, so it’s easy to write both files.
For Flow and vanilla, the easiest is to just generate Flow and ignore the types for vanilla. The requirement is to have eg Babel in the pipeline. But it’s simpler than having a third kind of file generated at the same time.

**Comment by cristianoc** [comment]
Branch for the final renaming: https://github.com/cristianoc/genFlow/pull/44.

**Comment by cristianoc** [comment]
Done.
