### ISSUE TITLE
Using gentype with Typescript Classes

### ISSUE THREAD

**Issue by idkjs** [cristianoc/genType#400]
Here is the reproduction:https://github.com/idkjs/gentype-ts-classes.
In this example binding from the this repo:
```
module AbsoluteValue = {
  [@genType.import ("./MyMath", "AbsoluteValue")]
  type t = {. "getAbs": (. unit) => int};


  /* This is untyped */
  [@bs.send] external getProp: t => int = "getProp";


  /* This is also untyped, as we "trust" the type declaration in absoluteVaue */
  let getAbs = (x: t) => {
    let getAbs = x##getAbs;
    getAbs(.);
  };
};
```

which binds to:

```
export class AbsoluteValue {
  public prop!: number;
  public getProp(): number {
    return this.prop;
  }
  public getAbs(): number {
    return this.prop < 0 ? -this.prop : this.prop;
  }
}
```

How do you instantiate an `AbsoluteValue.t` object?

In `.ts` I am able to do it like this:
```ts
let abs = new AbsoluteValue();
console.log("abs: ", abs);
console.log("abs.prop: ", abs.prop);

abs.prop = 1.1;
console.log("abs.prop: ", abs.prop);

console.log("abs.getProp: ", abs.getProp());
```

Which outputs:
```sh
abs:  AbsoluteValue {}
abs.prop:  undefined
abs.prop:  1.1
abs.getProp:  1.1
```

How would I do it on the reason side?

from https://github.com/cristianoc/genType/issues/398#issuecomment-604476202
> @idkjs indeed classes are the main kind of values that does no really have a 1to1 correspondence in Reason. So it seems that initialization is best done on the JS side, but the initialization function can then be imported into Reason.
> Essentially the class will be encapsulated as a functional API that Reason (or other TS code) can then use.
>

**Comment by cristianoc** [comment]
So from Reason it would look something like: `AbsoluteValue.create()` where `create` is defined in JS.

**Comment by idkjs** [comment]
So if we are starting from here:
```
module AbsoluteValue = {
  [@genType.import ("./MyMath", "AbsoluteValue")]
  type t = {. "getAbs": (. unit) => int};

  /* This is untyped */
  [@bs.send] external getProp: t => int = "getProp";

  /* This is also untyped, as we "trust" the type declaration in absoluteVaue */
  let getAbs = (x: t) => {
    let getAbs = x##getAbs;
    getAbs(.);
  };
};
```

Would we have to change `type t` to make that work?

Trying this:
```
module AbsoluteValue = {
  [@genType.import ("./MyMath", "AbsoluteValue")]
  type t = {. "getAbs": (. unit) => int};
  [@bs.new] external create: t = "prop";
  /* This is untyped */
  [@bs.send] external getProp: t => int = "getProp";

  /* This is also untyped, as we "trust" the type declaration in absoluteVaue */
  let getAbs = (x: t) => {
    let getAbs = x##getAbs;
    getAbs(.);
  };
};
```

**Comment by cristianoc** [comment]
It would be something like:
```reason
[@bs.new] external create: unit => t = "create";
```

**Comment by idkjs** [comment]
@cristianoc thanks for the help. I have it worked out [here](https://github.com/idkjs/learn-reason-ts-classes-gentype) in `src/index.re` calling the `src/MyMath.ts` file directly. Still have not figured out how to get `UseJsValue.re` to work. I assume there is some additional `tsconfig.json` setting for that. I would like to document what that is so if you get a chance to direct me on that, it would be appreciated. Thanks, again for your time, sir.

**Comment by cristianoc** [comment]
@idkjs one possibility is to start from this project `https://github.com/cristianoc/genType/blob/master/examples/typescript-react-example/src/UseImportJsValue.re` which should work.
Then only change what you need one small step at a time, and report if one change gets you into trouble.
