### ISSUE TITLE
Question about gentype.import support

### ISSUE THREAD

**Issue by bsansouci** [cristianoc/genType#406]
Hey @cristianoc first off let me say that genType is amazing. It was super easy to install and get working (once I figured out and copied the `.shims.ts` files) and it runs really quickly.

I'm trying to consolidate all of the types across our TS+Reason hybrid app, and genType.import seems like a useful way for me to write `external` to JS libraries, while also exporting a generated TS type for the TS side of the code. I actually _need_ both types to come from the same source instead of using the TS types that come with JS library because the types my ReasonML functions use need to match the types of the args to these functions. 

Here's what I got working so far, and I was wondering if there was a particular reason it worked the way it does:
<img width="2038" alt="Screen Shot 2020-04-03 at 12 05 04" src="https://user-images.githubusercontent.com/4534692/78396292-f93f0f80-75a3-11ea-9279-6ebfca6b710d.png">

The couple of things to note:
- I had to repeat the path to his value `firestore.Timestamp.fromDate` in two places
- I had to repeat the module name
- I could not inline the externals inside the `Timestamp` module, gentype would not generate an output object `export const Timestamp ...` like it does right now (middle tab)
- Because of the previous point, I had to re-assign like I did (without going through externals), but now as you can see in the right-most panel, bucklescript makes a wrapper function instead of inlining like it normally would

Here's what I wished I could do, and please tell me how unrealistic this is:
```reason
module Timestamp = {
  [@gentype] [@bs.module "firebase/app"] [@bs.scope ("firestore", "Timestamp")]
  external fromMillis: float => timestamp = "fromMillis";

  [@gentype] [@bs.module "firebase/app"] [@bs.scope ("firestore", "Timestamp")]
  external fromDate: Js.Date.t => timestamp = "fromDate";
};
```

I really do wish I could have one source for the types and values in my whole app, just to avoid repeats and keep things clear. Right now it's a mess (mostly my fault) because values and types come from 3 different places haha.

By the way, thanks to gentype I was able to nuke out of orbit a massive types.ts file in a matter of **minutes**, with _everything_ running smoothly. Fucking amazin.

**Comment by cristianoc** [comment]
@bsansouci thanks for the excellent question.
We can take it in steps, and perhaps can use a little sample project, if necessary.

First, have you tried omitting `bs.module` and `bs.scope` when using `@genType.import`?
The idea is that bs imports from `Thisfile.gen` and `Thisfile.gen` imports from the desired path.

**Comment by cristianoc** [comment]
Wrapper functions:
```
[@genType.import "./"] external gg: (. int) => int = "gg";
[@genType.import "./"] external zz: int => int = "zz";
```
Note `gg` is not wrapped but `zz` is.

**Comment by bsansouci** [comment]
To make sure I'm understanding what you're asking, you're saying I should try doing this:
```reason
[@gentype.import ("firebase/app", "firestore.Timestamp.fromDate")]
external makeTimestampFromDate: Js.Date.t => timestamp = "fromDate";
```
That doesn't seem to work, as bucklescript now doesn't know about it and warns: `BuckleScript warning: Unimplemented primitive used:fromDate`


And the wrapper function like so:
```reason
[@gentype.import "./"] external test: Js.Date.t => timestamp = "fromDate";
```
doesn't work either, because the generated TS isn't valid. It's complaining to me that it cannot find module "./". I'm not sure I'm understanding what you're suggesting with the wrapper functions, because without any bs annotations, bucklescript doesn't understand the externals.
Ideally I'd be able to write one single external that satisfies both languages. I'm not sure

**Comment by cristianoc** [comment]
About putting exports inside a module `Timestamp`. Note exports are not scoped: the value you reference is always the same, whether you put the external inside or outside `Timestamp`. So what does not change is that`Thisfile.bs` imports from the toplevel of `Thisfile.gen`.
This implies that: the names of externals need to be unique across the file anyway. But more importantly: the imported value won't be re-exported as a value inside `Timestamp`, but as a toplevel value.

Ideally, the language should have an external mechanism for modules, which does not exist today.

**Comment by cristianoc** [comment]
@bsansouci as anticipated, we need a little repo to dig more into this.

`@gentype.import` is understodd by bucklescript, which generates code that picks up the value from `Thisfile.gen`. And `Thisfile.gen` transitively picks it up from he indicated JS path.

**Comment by cristianoc** [comment]
As a diagram.

Take `Foo.re` with a `@genType.import`:
`Foo.bs ---> Foo.gen --> SomePath.js`

Take `Foo.re` with a `@genType` export:
`SomePath.js ---> Foo.gen ---> Foo.bs`

Take `Foo.re` with *both*  a `@genType.import` and a `@genType` export:

```
SomePath.js <---> Foo.gen <---> Foo.bs
```

This is the general picture to supprot, including making sure bundlers can resolve the file-circular dependencies.
