### ISSUE TITLE
Annotations on implementations of inner modules with interfaces are ignored, just as with `.re` and `.rei` files, but no warnings are issued.

### ISSUE THREAD

**Issue by TomiS** [cristianoc/genType#407]
Hi again. I noticed this behavior
```reason
// Works -> export type Test1_t = number;
module Test1 = {
  [@genType]
  type t = int;
};
// Works -> export type Test2_t = number;
module Test2: {
  [@genType]
  type t = int;
} = {
  type t = int;
};
// Does not work, nothing is generated
module Test3: {
  type t; // <- abstract type here
} = {
  [@genType]
  type t = int;
};
```
With the pattern in Test3 I'm trying to prevent initializing a variable without using the `make` function (not included in the example), but it's a bit awkward if genType does not recognize anything inside that module.

Is this intentional, impossible to fix or a valid bug?

**Comment by cristianoc** [comment]
@TomiS that looks like a bug.
It work for `.rei` and `.re` files. And something must be off for internal modules.

**Comment by cristianoc** [comment]
Oh wait.
In Test3 the annotation must be on the interface not the implementation.

**Comment by cristianoc** [comment]
I've recently introduced warnings for this case of annotations that will be ignored as they're are in a `.re` but `.rei` exists, but the warning does not fire for internal modules yet. This is probably a good time to extend that.

**Comment by TomiS** [comment]
Ah, I see. I haven't used `.rei` files at all yet. Maybe it's time to start to use them at least for my "important core types"

**Comment by cristianoc** [comment]
So in this case, it should be:
```reason
module Test3: {
  [@genType]
  type t;
} = {
  type t = int;
};
```

**Comment by TomiS** [comment]
@cristianoc I tested that the following notation does not produce any generated types.
```
module Test3: {
  [@genType]
  type t;
} = {
  type t = int;
};
```

Also this doesn't produce anything:
```
module type AbstractTest3 = {
  [@genType]
  type t;
};
module Test3: AbstractTest3 = {
  type t = int;
};
```

**Comment by TomiS** [comment]
If I use the separate `.rei` file like this:
```reason
// .rei interface
module Test3: {
  [@genType]
  type t;
};
```
```reason
module Test3 = {
  type t = int;
};
```
The type is generated but it is of `mixed` type:
```
export opaque type Test3_t = mixed;
```

**Comment by cristianoc** [comment]
@TomiS:
- "does not produce any generated types": there's an issue where the only annotation is in an interface file in an inner module (genType does not run). Would you export something else too? I'll take care of this separatey.
- "Also this doesn't produce anything:" -- module types are not supported for that use, so that's not surprising.
- re/rei: don't use an inner module, just the exported type, in the `.re` and `.rei` -- that was the intended situation to try.

**Comment by TomiS** [comment]
- Ok. Good to know. I can always export a dummy type in the root or something if needed.
- Ok, gotcha.
- If the type is in the root of `.re` and `.rei` files, a `mixed` type is generated unless the type is defined as a non-abstract type in the interface file.

**Comment by cristianoc** [comment]
Dummy type: it's already fixed in master, FYI, so it won't be needed for long.

**Comment by TomiS** [comment]
I'm experiencing another weird issue though... This code:
```reason
[@genType]
type dummy = string;

module Test3: {
  [@genType]
  type t;
} = {
  type t = string;
};

module ObjectId: {
  [@genType]
  type t;
  let make: string => t;
  let toString: t => string;
  let fromString: string => t;
  let t_encode: Decco.encoder(t);
  let t_decode: Decco.decoder(t);
} = {
  type t = string;
  let make = value => value;
  let fromString = value => value;
  let toString = value => value;
  let t_encode: Decco.encoder(string) =
    value => value->toString->Js.Json.string;
  let t_decode: Decco.decoder(string) =
    json =>
      switch (Js.Json.classify(json)) {
      | Js.Json.JSONString(str) => make(str)->Belt.Result.Ok
      | Js.Json.JSONNull =>
        "INVALID_ID"->Belt.Result.Ok;
      | _ =>
        "INVALID_ID"->Belt.Result.Ok;
      };
};
```
only generates this type:
```
export type dummy = string;

export opaque type Test3_t = mixed;
```
So there must be something in the latter more complex module that the genType does not like.

**Comment by cristianoc** [comment]
@TomiS : "a mixed type is generated unless the type is defined as a non-abstract type in the interface file" is the correct behavior. Were you expecting something else?

**Comment by TomiS** [comment]
@cristianoc Well, I guess I was expecting to see the type defined in the implementation because `mixed` does not add any value from type safety point of view and I think it might even conflict if I try to introduce more accurate types on the JS/Flow side of the codebase.

ps. If I remove the `fromString` function from the `ObjectId`, then the mixed type is generated. What's wrong with having a `fromString` function?!

**Comment by TomiS** [comment]
Yeah, now I'm actually getting an error from the ObjectId that looks like this:
```
Cannot create Foo element because string [1] is incompatible with ObjectId_t [2] in property featureId of
the first argument of property someFunction.

... code location here ...

     client-re/src/Core/Types.gen.js
 [2]  21│   +featureId?: ObjectId_t, 

     src/core/types.js
 [1] 109│   +featureId?: string,
```
So the `opaque mixed` type seems to not really work when a string is wanted elsewhere. I can probably hack around this but ofc would rather not :)

**Comment by cristianoc** [comment]
Ignore mixed: `opaque` is the important part. And it is opaque: you can't look into it.

**Comment by TomiS** [comment]
Ah, I see. I haven't really used `opaque` anywhere before this.

**Comment by TomiS** [comment]
I guess my case is exactly that. I want to allow creation of the value in Reason only through make function, hence the abstract type in the interface. But it should show as the actual type for JS/Flow. But if this is a "difficult to solve" kind of corner, then I can just get rid of my fancy abstract type and define them as they are. It's slightly less safe in Reason but still quite acceptable.

**Comment by cristianoc** [comment]
@TomiS for your larger example `module ObjectId...` it hits another corner case uncovered so far, fixed here: https://github.com/cristianoc/genType/commit/fb415d10f87384606c6380feea0be0bcc309e607

**Comment by cristianoc** [comment]
@TomiS for your use case of only exporting to JS, it's pretty rare but supported.
See https://github.com/cristianoc/genType/blob/master/examples/typescript-react-example/src/IgnoreInterface.rei and https://github.com/cristianoc/genType/blob/master/examples/typescript-react-example/src/IgnoreInterface.re.

**Comment by TomiS** [comment]
Hmm, I think there is something else involved too in the `fromString` case. I do define the `fromString` also in the interface, so the amount of values should be the same.

**Comment by cristianoc** [comment]
It's generally when there is a constraint between interface and implementation. Would you try your example and let me know?

**Comment by TomiS** [comment]
Sure, give me a moment.

**Comment by TomiS** [comment]
Ok, I'm quite sure it works as expected if I write exactly this:
Interface (`.rei` file)
```reason
type dummy = string;

type t;

module ObjectId: {
  type t;
  let make: string => t;
  let toString: t => string;
};
```
implementation (`.re` file):
```reason
[@genType.ignoreInterface]
[@genType]
type dummy = string;

[@genType]
type t = int;

module ObjectId = {
  [@genType]
  type t = string;
  let make = value => value;
  let toString = value => value;
};
```
output:
```js

export type dummy = string;

export type t = number;

export type ObjectId_t = string;
```
So the ignoreInterface needs to be in the implementation file, it seems.

**Comment by cristianoc** [comment]
@TomiS have you tried putting `[@genType.ignoreInterface]` in the `.rei` file? It should work.

**Comment by TomiS** [comment]
@cristianoc Yes, I tried, it did not work. I tried quite a few other combinations too.

**Comment by cristianoc** [comment]
But the example I pointed out does work, right?

**Comment by cristianoc** [comment]
I think this issue can be mostly closed. Though if possible I'd like to understand what's going on with `ignoreInterface` at some point.

**Comment by TomiS** [comment]
@cristianoc I didn't test that. But now that I implemented this in my real code base, I actually had to put the `[@genType.ignoreInterface]` in to the interface file. So I guess it works as expected.

Yeah, I agree this can be closed. Thank you again!

**Comment by cristianoc** [comment]
Thank you for the high quality reports. Really appreciated.
