### ISSUE TITLE
Make (sub)modules `genType`able

### ISSUE THREAD

**Issue by ryyppy** [cristianoc/genType#41]
Given following file `foo.re`:

```ts
/* foo.re */

module Bar = {
  let values = [1, 2, 3];
};
```
I want to be able to import this module in TypeScript like this:

```
/* test.ts */
import { Bar } from "foo.ts";
```

# My ideal fix

```ts
/* foo.re */

[@genType]
module Bar = {
  let values = [1, 2, 3];
};
```

Resulting TypeScript wrapper of `Bar`: `Js.t({."values": any})`
In case any of the module's values / types are annotated as well, it will refine the types. E.g.

```
/* foo.re */

[@genType]
module Bar = {
 [@genType]
  let values = [1, 2, 3];
};
```

Resulting TypeScript wrapper of `Bar`: `Js.t({."values": js(list(int))})`

# Concrete example (doing workarounds)

```ts
/* data.re */
module Organizer = {
  type t = { name: string };
  let organizers = [|
   {name: "organizer 1"},
   {name: "organizer 2"}
  |];
};

/* I need to flatten this value, so I can access it in plain JS */
let organizers = Organizer.organizers;
```

```txt
/* about.mdx */
import { organizers } from "./data.re";

# Organizers

Some text about our organizers.

<Organizers organizers={organizers} />
```

**Comment by cristianoc** [comment]
In this case, assuming there is no `Foo.rei`:
```reason
/* Foo.re */
[@genType]
module Bar = {
  let values = [1, 2, 3];
};
```
Any other Reason module can access `Foo.Bar.values` and *know* its type.
With the proposal above, a corresponding JS module would not have access to the type of `values`.
This is a semantic inconsistency that I would like to avoid.

I would like an external JS module to have exactly the same visibility as an external Reason module.
So if one wants to hide the type of `values`, then either `Bar` should be given an interface, or `Foo.rei` should do it.

**Comment by cristianoc** [comment]
The semantics I would give to `[@genType]` at the top of a module is that all the values in it are exported. So it does not give any extra expressiveness -- just an abbreviation for annotating all the elements inside the module.

**Comment by cristianoc** [comment]
I forgot to mention, there's also the annotation `@genType.opaque` which is not advertised yet. What this does is to give the exported value an opaque type . So instead of `any` it will be a type distinct from every other one, but opaque in that you don't know the internal representation.
(Opaque types are first-class in Flow, and can be represented with a little trick in TS).

In terms of expressivity, with `@genType.opaque` one can decide for each value separately, whether to export it and whether to expose its actual type, irrespective of whether it's in an inner module or not.

The downside, is that one has to learn an extra annotation. Not sure if the same expressivity can be obtained in a simpler way.

**Comment by cristianoc** [comment]
So I would distinguish 3 separate aspects:
1) Support accessing values defined inside inner modules.
2) Support exporting types as opaque.
3) Support a single annotation to export all values inside a module.

**Comment by cristianoc** [comment]
There's a fourth aspect covered in https://github.com/cristianoc/genType/commit/541cc9ce655e5981581380e4dd2c60f5e6908535:

4. Support nested modules in shim files.

This is about types in nested modules.
The type representing `ReactEvent.Mouse.t` is `Mouse_t` in shim module `ReactEvent`.

**Comment by ryyppy** [comment]
@cristianoc is this issue irrelevant by now?

**Comment by cristianoc** [comment]
It is still open as a possibility, though there are other ways to obtain the same effect.
One of the competitors is using the annotation on modules as a short-hand to annotate every item inside the module.

**Comment by cristianoc** [comment]
E.g. turning it into a first-class module achieves the desired format for export to JS.

**Comment by cristianoc** [comment]
Another comment is that the dual direction, importing a module from JS, does not seem feasible. As modules and functors are not things that can appear in externals. While functions on first-class modules can.

**Comment by cristianoc** [comment]
Closing this for now.
The meaning of annotating modules to be explored separately.
