### ISSUE TITLE
Allow uppercased types in Typescript backend

### ISSUE THREAD

**Issue by hejfelix** [cristianoc/genType#411]
I want to generate types for TypeScript, but there's no way to configure genType to output uppercased types (which is idomatic for TypeScript).

Is this possible? Could this be added?

**Comment by cristianoc** [comment]
```reason
[@genType]
[@genType.as "Props"]
type props = {
  x: int,
  n: string,
};
```

**Comment by cristianoc** [comment]
Tbh I'm not sure why `[@genType.as "Props"]` does not make the first line `[@genType]` optional.
That shortcut could be implemented.

**Comment by cristianoc** [comment]
Automatic mangling is not something that will be supported, as it generates lots of other problems.
However,  there are plans for a long term solution. Stay tuned.
