### ISSUE TITLE
Mixing conversions and submodule's isn't using the conversion

### ISSUE THREAD

**Issue by tomgasson** [cristianoc/genType#414]
```reason
[@genType]
type t =
  | A
  | B({name: string});

module X = {
  [@genType]
  let foo = (t: t) => {
    switch (t) {
    | A => Js.log("A")
    | B({name}) => Js.log("B" ++ name)
    };
  };
};

```

Gives
```tsx
type $any = any;

const $$toRE552311971 = {"A": 0};

// $FlowExpectedError: Reason checked type sufficiently
const CreateBucklescriptBlock = require('bs_block');

// $FlowExpectedError: Reason checked type sufficiently
const GenTypeBugBS = require('GenTypeBug.bs');

export type t = "A" | {| +name: string |};

const X_foo: (t) => void = function (Arg1: $any) {
  const result = GenTypeBugBS.X.foo(typeof(Arg1) === 'object'
    ? CreateBucklescriptBlock.__(0, Arg1)
    : $$toRE552311971[Arg1]);
  return result
};;
exports.X_foo = X_foo

const X: { foo: (t) => void, ... } = GenTypeBugBS.X;
exports.X = X
```

A call to `Module.X.foo("A")` won't use X_foo, it will use the BS.X.foo method directly

**Comment by cristianoc** [comment]
@tomgasson thanks for the report. Spot on.

**Comment by cristianoc** [comment]
@tomgasson do you actually need it, or is it just an issue you noticed?

We're moving towards zero conversion once the runtime representation of variants changes.
So here the fix would be to make a copy of the `.bs.js` module, which goes exactly in the opposite direction of the desired "zero runtime".

I'm tempted to just not generate the internal module when conversion is required.
So, these lines would just not be generated when parts of the module require conversion:
```ts
const X: { foo: (t) => void, ... } = GenTypeBugBS.X;
exports.X = X
```

**Comment by tomgasson** [comment]
Yeah, this is a real bug we hit. If we're already on a path to not need this that's great. It it's easy, not generating the X.foo type will make it hard to fall for this trap

**Comment by cristianoc** [comment]
@tomgasson see fix in https://github.com/cristianoc/genType/pull/416 where inner modules are not emitted when they require conversion.
If it looks good, I'll go ahead and merge.

**Comment by tomgasson** [comment]
Looks good. Thanks for the fix
