### ISSUE TITLE
Number or payload variant type?

### ISSUE THREAD

**Issue by TomiS** [cristianoc/genType#419]
In Flow (and probably in Typescript) it's possible to define a union of number and object like this:
```ts
type Payload = { foo: string, bar: number };
type NumberOrPayload = number | Payload;
```
Is it possible to do this already with genType? I didn't find a way.

If not, here's a proposal. Maybe allow writing like this:
```reason
type payload = { foo: string, bar: int };
type numberOrPayload = [
  | [@genType.as number] `someVariant(int)
  | `anotherVariant(payload)
];
```
That would map any number automatically into the variant given in the type.

I don't know if this is technically possible, but it'd be useful if it is.

**Comment by cristianoc** [comment]
We're moving towards a transparent treatment of variants which corresponds to what bucklescript does (https://github.com/BuckleScript/bucklescript/issues/4307). Best to follow those developments.
genType will follow that runtime representation, so to have zero conversion at the interface.

**Comment by TomiS** [comment]
Okay. Thanks for answering.

**Comment by cristianoc** [comment]
@TomiS to give more context, the bootstrapping phase of genType is complete.
The current phase, as far as runtime representation is concerned, is about blending in with the bucklescript choices as much as possible. So it will adopt whatever runtime representation of variants bucklescript will choose (this was not possible in the past).
So removing genType-specific features will be prioritized over adding features. And gradually blend into a single unified experience.

**Comment by TomiS** [comment]
@cristianoc This sounds like a novel plan to me, at least on high level. Still, I'd like provide a friendly reminder from the "ground floor", that most users are probably using genType to attempt to migrate a large real life Typescript/Flow project to Reason and will eventually only care if they are able make existing legacy types (used in many places) match to new Reason types (initially a minority). So I hope the grand plan aligns with this need.

**Comment by cristianoc** [comment]
It does in fact. The plan is to make it possible to bind variants to the typescript representation. This can be done directly at the compiler level.
Without that, for instance, you cannot bind to mutable objects, because conversion implies copy.

**Comment by cristianoc** [comment]
Also if any conversion is involved, then any function using it needs to be wrapped. It means memorization on that function is broken.
Just listing a few reasons for the plan.

**Comment by TomiS** [comment]
Oh, sounds pretty cool indeed.
