### ISSUE TITLE
Convert Reason record to TypeScript interface with the first letter being uppercased

### ISSUE THREAD

**Issue by nikgraf** [cristianoc/genType#42]
This is a duplicate of https://github.com/cristianoc/genTypeScript/issues/4, but I guess since genFlow is the future I post it here again:

In TypeScript it's common that the first character of types and interfaces is upper-case.

Reason
```js
type person = { name: string };
```

Ideally would be converted to

```ts
interface Person { name: string };
```

Why Interfaces? They offer more capabilities compared to a type declaration e.g. extending them.

**Comment by cristianoc** [comment]
In terms of trade-offs, those are the positives.
The negatives include:
- need to remember to capitalize/uncapitalize the same type when accessed from Reason vs JS.
- not every type can be made an interface. E.g. `type t = int`, so the price to pay is a bit of inconsistency.

Overall, I'm not sure.

**Comment by nikgraf** [comment]
Totally can see the capitalize/uncapitalize overhead, but on the other hand for any TypeScript user anything uncapitalize looks surprising.

Yeah the fact that you can represent an object as type or interface is one of the many things from my pov that make TypeScript not straight forward to use in the day to day.

My assumption is: If genType doesn't generate idiomatic TypeScript, it will be hard to convince TypeScript teams to adopt Reason.

**Comment by cristianoc** [comment]
Idiomatic is definitely high up on the priority list.
I'd just like to explore things a bit further first.

Interfaces can be extended. When an extended value is passed into Reason and later gets back into JS, it will change representation into Reason records and back to JS objects. This means, that any extra fields will get lost. This could be surprising as typically in JS one would pass the whole object, while crossing the JS/Reason interface means the value is copied.

**Comment by jchavarri** [comment]
One idea would be to only allow to export an `interface` from `Js.t` objects, as those don't need to be converted on the boundaries. The downside is that it'd require for the Reason author to explicitly annotate the functions where these types are used, but I think it could be worth it as objects seem to be closer in nature to Flow / TS interfaces than records.

Another (non mutually exclusive) idea is to make the interface generation opt-in with some special annotation like `[@genType.interface]`.

**Comment by cristianoc** [comment]
See this test https://github.com/cristianoc/genType/pull/81 about how exporting types as interface would look like.

There are a few questions on how this could be deployed, including whether it should be per-project or even per-instance with a dedicated annotation `[@genType.interface]`.

In the test, the types are also capitalized, adding a "I" to the name. This is just one possible way. The "I" is a recommendation coming form the TS linter.

The test also applies to Flow, where one observation is that where interfaces are used, one loses the opportunity to emit `exact` object types `{| ... |}`.

**Comment by cristianoc** [comment]
Another observation is that if a type is capitalized when exported as an interface (and perhaps "I"-prefixed), then this becomes visible from JS. It means if a type is changed from object to something simpler, its name changes too.
