### ISSUE TITLE
Typescript generic

### ISSUE THREAD

**Issue by Coobaha** [cristianoc/genType#420]
Hi @cristianoc 

On TS side I have following code:
```typescript
// MyInput.tsx
type Props = InputHTMLAttributes<HTMLInputElement>; 
...component code
```

```reason
[@genType.import "./MyInput"]
[@react.component]
external make:
  (~onFocus: ReactEvent.Focus.t => unit=?) => React.element =  "default";
```

In genType output `onFocus` will be more general than TS version of `onFocus` which is obviously a type error. (`Element` vs `HTMLInputElement`).

What is a recommended approach to handle this? Should I do some shims juggling? Thanks!

**Comment by Coobaha** [comment]
I've ended adding this to `ReactEvent.shim.ts`
```
export type inputFocus = React.FocusEvent<HTMLInputElement>;
export type inputChange = React.ChangeEvent<HTMLInputElement>;
export type inputKeyboard = React.KeyboardEvent<HTMLInputElement>;
```

And  using it on reason side as
```
[@genType.import "../src/ReactEvent.shim"]
type inputFocus = ReactEvent.Focus.t;
[@genType.import "../src/ReactEvent.shim"]
type inputChange = ReactEvent.Form.t;
[@genType.import "../src/ReactEvent.shim"]
type inputKeyboard = ReactEvent.Keyboard.t;

...

    ~onBlur: inputFocus => unit=?,
    ~onFocus: inputFocus => unit=?,
    ~onChange: inputChange => unit=?,
    ~onKeyPress: inputKeyboard => unit=?,

```

Maybe it would be nice to be able to provide generic in place?

```
    ~onBlur: [@genType.generic "HTMLInputElement"] ReactEvent.Focus.t => unit=?,
    ~onFocus:[@genType.generic "HTMLInputElement"] ReactEvent.Focus.t => unit=?,
    ~onChange: [@genType.generic "HTMLInputElement"] ReactEvent.Form.t => unit=?,
    ~onKeyPress: [@genType.generic "HTMLInputElement"] ReactEvent.Keyboard.t => unit=?,
```

Which would result in whatever payload string was provided to be inlined to TS output?

**Comment by cristianoc** [comment]
@Coobaha thank you for looking into it.
Are you happy with your solution?
If so, is it general?
Then would you open a PR to make it into the example shims of the genType sample project?

**Comment by Coobaha** [comment]
I am happy that it is quite easy to add and flexible, but requires using of shims. Obviously supporting this from genType to cover all the cases like imports would require more work. I will add this to examples

**Comment by cristianoc** [comment]
@Coobaha depending on what are the types, this is also pretty straightforward to add internally:
https://github.com/cristianoc/genType/blob/master/src/TranslateTypeExprFromTypes.re#L155

**Comment by Coobaha** [comment]
> Then would you open a PR to make it into the example shims of the genType sample project

@cristianoc done #421

**Comment by cristianoc** [comment]
Thanks!
