### ISSUE TITLE
Property 'opaque' has no initializer and is not definitely assigned in the constructor.

### ISSUE THREAD

**Issue by aurerua** [cristianoc/genType#53]
Following on the TypeScript example to integrate Reason to a TypeScript React project, I get the following error in `ReasonPervasives.shim.ts` from TypeScript:
```
Property 'opaque' has no initializer and is not definitely assigned in the constructor.
```
It comes from this bit of code: 
```ts
export abstract class Cons<T> {
  protected opaque: T;
}
```
VSCode proposes two possible fixes: 
- Add `undefined` type to property `opaque`
```ts
export abstract class Cons<T> {
  protected opaque: T | undefined;
}
```
- Add definite assignment assertion  to property `protected opaque: T;`:
```ts
export abstract class Cons<T> {
  protected opaque!: T;
}
```
Is one solution, or both, okay? Is one better than the other? why?

**Comment by cristianoc** [comment]
@aurerua how's the TypeScript project configured? I would like to repro that error locally, so it won't come back.

**Comment by cristianoc** [comment]
Actually, found it:
```
    "strictPropertyInitialization": true
```
