### ISSUE TITLE
[@genType] with None produces output that Flow can't type check

### ISSUE THREAD

**Issue by jchavarri** [cristianoc/genType#61]
I was trying to expose `Some` and `None` to JS code. `Some` works great, but I found this output with None:

Input (.re):

```reason
[@genType]
let none = None;
```

Output (.re.js):

```js
export const none: ?T1 = OptionBS.none;
```

Then Flow fails to type check in any case as there's no way to define T1. I know this case is tricky from a type perspective as there is no output info about the result. But maybe this should be reflected in the output somehow? Maybe not producing anything and showing an explanatory comment, or exposing the value as function:

```js
const none = <T1>(a: T1): ?T1 => OptionBS.none;
```

to be able to fill the type param.

**Comment by cristianoc** [comment]
@jchavarri can you expand a bit on what you wanted to do when you encountered this: why did you want to expose `None`?.
As you've seen, there's no type one can give it which corresponds to the Reason polymorphic type, as that's only possible for function types. (Forcing `None` into a function is problematic, as you need to supply a value for that function exactly when you don't have none).
On the JS side, you can always use `undefined` (and most times `null` to, when it's allowed and the type checker lets it through) for `None`. In fact, in Js you don't need to know of the existence of option types, and work with the types that genType gives you.

**Comment by jchavarri** [comment]
Sure! I was exploring how to expose some `Belt` modules to JavaScript files, and I started with `Belt.Option`. So exposing functions like `flatMap` and `map` worked perfect, but then I was thinking about creating values from JS and how to expose `Some` and `None`.

Maybe what I'm trying doesn't make sense.... but I can think of other cases of variant types that have a type variable as input and one of the constructors doesn't use it.

**Comment by jchavarri** [comment]
Another case, if it helps somehow:

```reason
[@genType]
let empty = Belt.Map.String.empty;
```

generates

```js
export const empty: Belt_Map_String_t<T1> = MapStringBS.empty;
```

Which has `T1` that Flow fails to resolve.

**Comment by jchavarri** [comment]
Ah, I just realize that I can expose these values through a function and then it's fine. :)

```reason
[@genType]
let empty = () => Belt.Map.String.empty;
```

```js
export const empty: <T1>(void) => Belt_Map_String_t<T1> = MapStringBS.empty;
```

**Comment by cristianoc** [comment]
Yes, that's the way to go.
Would you add a sentence in the README to document this?
