### ISSUE TITLE
Exposing module types

### ISSUE THREAD

**Issue by MarcelCutts** [cristianoc/genType#64]
I've been experimenting with mixing ReasonML and regular JS to provide a solid foundation across side effects.

One thing that I would find amazingly useful is being able to run `genType` on types within instantiated modules so I can expose those to regular `flow`d components

A reason-apollo example

```ocaml
[@genType]
module GetUser = [%graphql
  {| query getUser { user { firstName, lastName, telephone } }|}
];

module GetUserQuery = ReasonApollo.CreateQuery(GetUser);

[@genType]
type responseType = GetUser.t;
```

Here responseType ends up being

```js
export opaque type responseType = GetUser_t;
```

where `GetUser_t` cannot be resolved.

Is this something that's on the roadmap? Or is it one of those things that is actually rather difficult?

**Comment by cristianoc** [comment]
@MarcelCutts What's in `GetUser.t`? Would a more direct repro just involve writing a small `GetUser` module directly, or is a functor application required for a small repro?

**Comment by MarcelCutts** [comment]
A had a quick play - a functor is not required. Simplified test case below:

```ocaml
module A = {
  type user = {name: string};
};

[@genType]
type b = A.user;
```

Generated flow type:

```js
export opaque type b = A_user;
```

Where "A_user" cannot be resolved.

**Comment by cristianoc** [comment]
Adding one more report received for the same underlying issue : "there's no decent way to tag an included modules' type with [@genType]".
The situation is that there's a module you can't modify and ideally would add an annotation to. In this case, `user` is not annotated so it's not exported.

**Comment by cristianoc** [comment]
There's some annotation real estate planned but not used yet. Perhaps the annotation of modules could be used to mean that all the items within are annotated.

The real estate is a bit crowded though, as the annotation on modules could also be used to indicate grouping elements as objects: https://github.com/cristianoc/genType/issues/63.

**Comment by cristianoc** [comment]
@MarcelCutts, quite a lot of re-thinking and re-factoring later, see:
  https://github.com/cristianoc/genType/commit/a1bf47a077b497e777f3c6357b7a5c3422a9d05c

It addresses your little repro -- not sure exactly what the original problem generates, but can take a look if there are more details.

**Comment by MarcelCutts** [comment]
I've been watching the progress, absolutely amazing work!

This solution does indeed tackle the simplified problem, but my original use-case still doesn't quite work as intended. 

Summary 
1. We want to fetch data using reason-apollo
2. Possible responses are pre-typed by introspection of graphql schema
3.We would like to export these types as part of a ReasonReact component

Now we can do in-file static module declarations great, but it turns out functors are required and can't be subverted in these external libraries.

Test case

A.re
```ocaml
module type AConfig = {type configType;};

module A = {
  module Make = (Conf: AConfig) => {
    type a = Conf.configType;
  };
};

module B =
  A.Make({
    type configType = int;
  });

[@genType]
type c = B.a;
```

A.re.js
```js
import type {a as B_a} from './B.re';

export opaque type c = mixed;
```

However `B.re` does not exist.

Again, I want to emphasis a strong appreciation for the effort on this project. It's fantastic. 👍

**Comment by MarcelCutts** [comment]
For additional context, I have dug up the "in anger" source from `graphql-ppx`.

The `type t` at the bottom is what holds the response type, and what I want to export into exist React components so they can get similar type safety from one source of truth.

**Comment by cristianoc** [comment]
After this https://github.com/cristianoc/genType/commit/9d99c5e2689569b4892e613d7471ed35ffc5a8a6, and the previous commit, it might be worth having another go and see if a more complex repro is required or the one provided was representative.

The last repro goes through now.

**Comment by MarcelCutts** [comment]
No luck yet but it feels tantalisingly close. Our original use case is still not quite good to go.

```ocaml
module GetUser = [%graphql
  {| query getUser { user { firstName, lastName, telephone } }|}
];

module GetUserQuery = ReasonApollo.CreateQuery(GetUser);

[@genType]
type responseType = GetUser.t;
```

```js
import type {t as MT_Ret_t} from './MT_Ret.re';

export opaque type GetUser_t = mixed;

export type responseType = GetUser_t;
```

I haven't quite been able to figure out why this one doesn't work but my test case (even when split across files) work great.

I will spend a bit of effort trying to understand and create a suitable trimmed down test case.

**Comment by cristianoc** [comment]
Btw there’s a little trick: generate the .mli interface automatically, and then look at what the generated types look like.
That’s already quite useful.

**Comment by cristianoc** [comment]
In case it helps: https://github.com/cristianoc/genType/commit/57628ea79bcc3e14765c2756a828233c704151d1 for (some) first-class modules, and module include.
So the surface of what's supported is bigger.

**Comment by MarcelCutts** [comment]
It works! 🎉

```ocaml
module GetUser = [%graphql
  {| query getUser { user { firstName, lastName, telephone } }|}
];

module GetUserQuery = ReasonApollo.CreateQuery(GetUser);

[@genType]
type responseType = GetUser.t;
```

now becomes

```js
export type GetUser_MT_Ret_t = {|+user: {|
  +firstName: string, 
  +lastName?: string, 
  +telephone: number
|}|};

export type GetUser_t = GetUser_MT_Ret_t;

export type responseType = GetUser_t;
```

And everything is fantastic. Thanks again for the diligent effort on this.

**Comment by cristianoc** [comment]
Awesome, this was fun. Thanks for the perseverance.
I guess some module include is generated, perhaps to splice in gql fragments.

**Comment by MarcelCutts** [comment]
Since everything is resolved I'm happy to close this issue ✅
