### ISSUE TITLE
No currying in ReasonReact runtime

### ISSUE THREAD

**Issue by rickyvetter** [cristianoc/genType#65]
When `genType` encounters a React component it generates a conversion wrapper that calls `make` directly. It doesn't use currying, so the generated output can be unsafe if BuckleScript doesn't optimize the `make` call to be an uncurried JS function.

Example:
```reason
let component = ReasonReact.statelessComponent("Component");

[@genType]
let make = (~count) => {
  Js.log(count);
  _children => {
    ...component,
    render: _ =>
      ReasonReact.string("Component that needs curried call" ++ string_of_int(count)),
  };
};
```

```js
function make$1(count) {
  console.log(count);
  return (function () {
      return /* record */[
              /* ... React component internals here ... */
            ];
    });
}
```

```js
export type Props = {|count: number, children?: mixed|};

const component: React$ComponentType<Props> = ReasonReact.wrapReasonForJs(
  MyFileBS.component,
  (function _(jsProps: Props) {
     /* problematic call here: */
     return MyFileBS.make(jsProps.count, jsProps.children);
  }));;
exports.component = component
```

**Comment by cristianoc** [comment]
Discussed offline. The only safe thing to do is to always assume that the `make` function could be curried, and generate a curried call.
This safety net should not incur excessive additional cost, considering that this only applies to Reason components wrapped for use by JS, and that there's already the cost of the component wrapping.
