### ISSUE TITLE
Support for tuples

### ISSUE THREAD

**Issue by jchavarri** [cristianoc/genType#68]
I've observed that tuples are not yet supported. Tuples are implemented as arrays in all Flow, TypeScript and BuckleScript so it _seems_ something that could be done without going through many loops...

Is there anything from a type system perspective that is preventing this feature?

If there are no blockers and it's not something that is being worked on at the moment, I would like to take a stab to get more familiar with genType code 😄

**Comment by cristianoc** [comment]
Definitely.
I was going to suggest having a go then read your last sentence 😄
