### ISSUE TITLE
Generate bindings in windows

### ISSUE THREAD

**Issue by matystl** [cristianoc/genType#72]
After puting binary in correct path and adding path to bs-compiler and runing build generated bindings has incorrect path(node can't recognize it)
```
/* Untyped file generated by genType. */

const Curry = require('bs-platform/lib/js/curry.js');

const ReCounterBS = require('.\ReCounter.bs'); <---- THIS IS NOT CORRECT
```
i manualy changed it to 
```
const ReCounterBS = require('./ReCounter.bs');
```
and it start working

**Comment by cristianoc** [comment]
So it looks like using a portable file name library is the wrong thing to do here, as also mentioned
https://github.com/nodejs/node-v0.x-archive/issues/5707

So this is wrong:
```reason
Filename.concat(Filename.current_dir_name, "ReCounter.bs")
```

**Comment by matystl** [comment]
Tested and it is working

**Comment by cristianoc** [comment]
@matystl that's great.
Are there any `\` in the require paths anywhere?

**Comment by cristianoc** [comment]
Merged.
