### ISSUE TITLE
Invalid JS code when packages have dashes

### ISSUE THREAD

**Issue by arnarthor** [cristianoc/genType#84]
When using `genType.import` with an npm package that has dashes in the name the generated JS code becomes invalid.

Example

```ocaml
[@genType]
type visible = [ | [@genType.as "auto"] `visible | [@genType.as "0"] `hidden];

[@genType.import "react-animate-height"] [@bs.module "./AnimateHeight.re.js"]
external make:
  (~duration: int, ~visibility: visible, 'a) =>
  ReasonReact.component(
    ReasonReact.stateless,
    ReasonReact.noRetainedProps,
    ReasonReact.actionless,
  ) =
  "default";

let make = make;
```

for untyped output becomes

```js
/* Untyped file generated by genType. */

const ReasonReact = require('reason-react/src/ReasonReact.js');

const react-animate-height = require('react-animate-height');

// In case of type error, check the type of 'make' in 'AnimateHeight.re' and the props of 'react-animate-height'.
export function react-animate-heightTypeChecked(props) {
  return <react-animate-height {...props}/>;
}

// Export 'make' early to allow circular import from the '.bs.js' file.
export const make = function _(duration, visibility, children) { return ReasonReact.wrapJsForReason(react-animate-height, {duration: duration, visibility: $$toJS1053365315[visibility]}, children); };

const $$toJS1053365315 = {"589592690": "auto", "-862584982": "0"};
```

Where `const react-animate-height` is an invalid name for a variable.

**Comment by arnarthor** [comment]
I can hotfix this in my code by creating a file called `reactAnimateHeight.js` that just default exports the npm package for now.

**Comment by cristianoc** [comment]
@arnarthor thanks for the report!
This should fix it: https://github.com/cristianoc/genType/commit/39178216b5e1a21b19915a3a8bab5d960e047b47.

Anything else to sanitize?

**Comment by arnarthor** [comment]
That is one amazing turnaround time 👌

This is perfect, haven't seen anything else so far but I'll create more issues as I use it more.

Just started integrating this into a decently sized project today, so we'll probably use it pretty heavily in the coming weeks. Looks really good so far at least

**Comment by cristianoc** [comment]
Great. If you find anything else, just let us know.
