### ISSUE TITLE
Consider add gentype suffix to generate file name

### ISSUE THREAD

**Issue by nhducit** [cristianoc/genType#86]
Current behavior

source file:
```
Greeting.re
```

generate 2 files:
```
Greeting.bs.js
Greeting.tsx
```

Motivation:
I don't want to add `Greeting.bs.js` and `Greeting.tsx` to git repository. For `.bs.js` files it is quite easy to add them to `.gitignore` file. But for generated tsx files, there is no easy way to know which tsx file is generated by `genType`.

Propose changes:
- Change generate file name from `Greeting.tsx` to `Greeting.xxx.tsx`. for example: `Greeting.gentype.tsx` for `Greeting.gt.tsx`
- This rule should apply for `ts` files also
- Should we apply this rule for flowtype?

Impact:
- It is a breaking change

**Comment by cristianoc** [comment]
See how things would look like in https://github.com/cristianoc/genType/pull/87.
Feel free to play with that and report back.
It's definitely possible to make the extension configurable.

**Comment by ryyppy** [comment]
I just opened the issue tab to propose a similar problem for `.re.js` files.
It would be cool if the user could configure the file-extension in the `bsconfig.json / gentypeconfig` section.

That would be especially useful in environments where you can't manipulate the resolver logic, like with `create-react-app`.

**Comment by cristianoc** [comment]
@ryyppy added configuration option, e.g. `    "generatedFileExtension": ".gt"`

**Comment by cristianoc** [comment]
This is now in master.

**Comment by nhducit** [comment]
wow. it is super fast. Thank you @cristianoc @ryyppy
