### ISSUE TITLE
Import nested values from JS.

### ISSUE THREAD

**Issue by cem2ran** [cristianoc/genType#96]
I've been looking into testing genType on a larger project and currently I'm unsure about how to import it when it's deeply nested in JS objects. Here's an example:
https://github.com/FiberJW/reason-expo/blob/6be95471afd0ce0b88b8bb92d371c9692b88a08d/src/Camera.re#L5

**Comment by cristianoc** [comment]
@cem2ran would something like this work?

```reason
[@genType.import "expo-camera/src/Camera"]
[@genType.as "Constants.Type"]
[@bs.module "./TestImport.gen"]
external cameraType: Js.t(_) = "";
```

which generates

```js
// flowlint-next-line nonstrict-import:off
import {Constants as cameraTypeNotChecked} from 'expo-camera/src/Camera';

// In case of type error, check the type of 'cameraType' in 'TestImport.re' and 'expo-camera/src/Camera'.
export const cameraTypeTypeChecked: Js_t<mixed> = cameraTypeNotChecked.Type;

// Export 'cameraType' early to allow circular import from the '.bs.js' file.
export const cameraType: mixed = cameraTypeTypeChecked;
```

**Comment by cristianoc** [comment]
This should take care of the use case:
  https://github.com/cristianoc/genType/commit/df0d810eb49d166759d8fdda2bb6623d786b0979
Let me know if that works for you.

**Comment by cristianoc** [comment]
Closing optimistically.
If the use case is not completely covered, or if related issues come up, feel free to reopen.
