### ISSUE TITLE
Renaming exported opaque types

### ISSUE THREAD

**Issue by benadamstyles** [cristianoc/genType#98]
I'm trying to do the following (using v1.1.0), but I don't think it's supported yet?

```reason
[@genType.opaque]
[@genType.as "DateKey"]
type dateKey = string;
```

**Comment by cristianoc** [comment]
Indeed.

**Comment by cristianoc** [comment]
@benadamstyles now works in v1.2.0.

**Comment by benadamstyles** [comment]
Hi @cristianoc – thanks so much for getting this in so quickly. Unfortunately (unless I'm doing something wrong), what happens now is that the type gets renamed at the export, but not when used elsewhere in the file. So this:

```reason
[@genType.opaque]
[@genType.as "DateKey"]
type dateKey = string;

[@genType]
let getMockDateKey = (key: string): dateKey => key;
```
becomes this:
```js
export opaque type DateKey = mixed;

export const getMockDateKey: (string) => dateKey = DateBS.getMockDateKey;
```

**Comment by cristianoc** [comment]
Oops you're right. Too quick.

**Comment by benadamstyles** [comment]
@cristianoc Yes this seems like the perfect solution!
